### ISSUE TITLE
Add permalinks to all elements (optionally)

### ISSUE THREAD

**Issue by oscarlevin** [rbeezer/mathbook#1016]
For an instructor, being able to direct a student to a precise example, exercise or even paragraph can be very useful.  When everything has a permid, this is possible, except that it is challenging to get access to the permid and full link.  The permalinks currently attached to divisions would be a good solution, if they were made available for all elements with a permid.  

This could be implemented just for an instructor edition (via logging in as an instructor), or using invisible links that only instructors know to look for (although this might be an accessibility issue).

**Comment by kcrisman** [comment]
👍

**Comment by aluminum1** [comment]
For permalinks, I suggest the following (similar to Wikipedia):

* Pretty much everything can be permalinked (paragraphs, sections, subsections, equations)
* No clutter by displaying extra symbols (eg. pillcrows)
* When you click on the element, the address bar in the browser gets changed to the permalink for that element, eg. book/defn_of_integral#Riemann_defn
* As a result, the browser will reload the page, being "centred" on that element
* The user can copy and paste the address in the browser.

That's it. Most students / instructors will find this out for themselves (they will click on the element, observe that the browser address bar has changed, and simply copy and paste it).

**Comment by davidfarmer** [comment]
I looked at Wikipedia and could not replicate that behavior.

I went to the Lady Gaga wikipedia page:

https://en.wikipedia.org/wiki/Lady_Gaga

and scrolled down to the heading:

2015–2017: American Horror Story, Joanne, and Super Bowl performances

When I click on it, nothing happens (for me, in Firefox on a MacBook).

Is some plugin needed?

Also, is there some clue to that behavior, or do you just have to know
that it works that way.

**Comment by aluminum1** [comment]
Yes. I should have said "kind of similar to Wikipedia". I just meant that, similar to my suggestion,  Wikipedia has:

* no displayed "permalink glyphs" i.e. pillcrows
* a hashtag mechanism for referencing the position on the page

The system seems to have worked well for them. Most people seem to be able to figure out how to get a permalink to a section on Wikipedia. Generally I guess they click on the "Table of Contents" bar and then perhaps they notice that the address bar changes. Or else they use the hash-tag mechanism and "guess" the permalink.

I know in our case it will be different. We have greater ambitions (wanting to have permalinks at a more granular level than sections, eg. individual equations, paragraphs). And we have no "Table of Contents" section on a page, at least not in the default setup.

But I think it might work. I think someone who is looking for a permalink will, as a first attempt, try to click on the object. He/she will then notice that the browser recentred itself to that object and the address changed. And so they will then realize "ok, that's a permalink" and just copy and paste it.

**Comment by Alex-Jordan** [comment]
In HTML, if there is an element of the page with attribute `id="foo"`, then attaching `#foo` to the end of a URL will tell a browser to bring focus to that element.

PreTeXt puts `id` attributes on titles. So you can create a targeted link if you know how to look inside the HTML source to see that `id`. But the practical issue has been that until recently, an `id` is likely to be something like `section-72` where the 72 is automatically generated since it's the 72nd section in the book. That is impermanent. Next week it might be `section-73`. So it could be bad to email students links to `...#section-72`.

If the author put an `xml:id` on the section, then that is used as the HMTL id instead. Now something fairly permanent is the HTML id, and in that scenario, you currently see the pilcrow, giving an easy way to get to the more targeted link than looking inside the HTML source.

That's the story of how we got here. Now we have `permid`~s as well as `xml:id`~s (but you need to have reached a point where you declare an edition). That development removes the concern about impermanent URLs, so more permalinks could exist by default. How to deliver them to the reader and make the reader aware that they exist gets into the pilcrow option versus any other ideas.

**Comment by drewyoungren** [comment]
Pinging this issue. (similar #138 )

**Comment by davidfarmer** [comment]
Planning this as a feature when logged in as an instructor.

**Comment by rbeezer** [comment]
We now have rather extensive permalinks on items in HTML output.  Improvements can be suggested on the lists or noted in new issues.
