### ISSUE TITLE
Change how Sage code is implemented in LaTeX

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1027]
* A Sage example via the `listings` package inside a technology block via the `tcolorbox` package can lead to invisible text.
* Discussion and debugging at:  https://groups.google.com/d/topic/pretext-support/BdF2p2TB9rQ/discussion
* Confirmation and fixes at: https://tex.stackexchange.com/questions/308672/why-is-text-turning-white-possible-scope-leak-after-page-break-and-listings

Perhaps using `tcblisting` is the way to go?

**Comment by kcrisman** [comment]
You found the 🔑 to the problem!

**Comment by kcrisman** [comment]
Comment: This is probably also closely related to #803 which was closed quite a while ago, though perhaps erroneously.

**Comment by kcrisman** [comment]
Comment just so I can find this when searching: this sort of thing seems to come up a lot more with `xelatex` than `pdflatex`.

**Comment by kcrisman** [comment]
Another story - I think it may be pretty difficult to avoid, and it really keeps people from using `xelatex` even when it will be necessary - maybe someone writing an entire book in a non-Roman character set?  I ended up with another example of this (after many intervening changes, of course) miles away from the previous location, and where as far as I can tell there are no such "interrupted" Sage cells.

In this case, there is an "example" with lots of Sage stuff in it, and the words after the example - halfway down the page! - all were white. The example crosses a page boundary, but none of the individual cells.  Interestingly, as soon as a hyperlink (in this case, an xref) appears, then all is normal!  In the same paragraph as the white content!

But changing the example to be much shorter (all the content is the same; only where the end tag for example changed location, and even the page break is in the same place) made things appear.

Just reporting in case that somewhat different context rings a bell, but I will keep messing around with it because I don't think there is anything immediate you could/would do at this time.  Another thought is that the "missing" `\par` after Sage cell outputs might help here, though of course that would be a hack since the underlying bug in `xelatex`+`listings` is still there.

**Comment by kcrisman** [comment]
Is this fixed now?  I think according to the lists and experience the answer was yes, but I forget if there were other issues as well.

**Comment by rbeezer** [comment]
Yes, thanks.  At 6040dbbf4e67381d34858ba6d9dfaa1293ff261f with some subsequent tweaks.

**Comment by kcrisman** [comment]
Still occurred!  Sending you hopefully-helpful code off-list - in this case, it is before and after a Sage cell, but the white space and the Sage cell all live on the same page (and there is wording appearing properly both before and after it).  In fact, it even crosses a subsection boundary - begins at the end of an example and ends at the beginning of a fact.
