### ISSUE TITLE
Option to float images

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1038]
Some publishers have a model where they revise the PDF
repeatedly and do not have the time to carefully place the
images to ensure good page breaks.    Those publishers would
appreciate a parameter that globally sets all figures to float.

This option would not be the default, and would be discouraged
for most publishers.

Some background here:
https://groups.google.com/forum/?hl=en#!topic/pretext-support/ZSHzG5hCNsM

**Comment by rvdg** [comment]
Thank you for opening the issue.  Notice that I do not suggest there be a global switch to make all figures to float.  It would be vey important to be able to do so on a figure-by-figure basis.  Small figures are often best placed exactly where they occur in the text.  It is larger figures that should be able to float.  

Having thought about this, I believe the simplest solution would be to allow an option `latexfloat="??"' where ?? is exactly what is placed in the option to '\begin{figure}[??]'.

Having said this, I could live with the global option you suggest.

**Comment by rbeezer** [comment]
@rvdg - I'm agreeable to try something like  `latex.float tb` where the `tb` could be any allowed string.  I think it needs to be provisional, since I have not yet integrated figures into the tcolorbox styling scheme.  So maybe `debug.float` at first, with no guarantees.

Would you be able to do an experiment?

Generate your *.tex, search for `placement={H}` and try replacements by just processing the LaTeX?  Look for anything unusual with placement or numbering?  Then we can go from there.

**Comment by rvdg** [comment]
> On Apr 8, 2019, at 11:22 PM, Rob Beezer <notifications@github.com> wrote:
> 
> @rvdg <https://github.com/rvdg> - I'm agreeable to try something like latex.float tb where the tb could be any allowed string. I think it needs to be provisional, since I have not yet integrated figures into the tcolorbox styling scheme. So maybe debug.float at first, with no guarantees.
> 
> Would you be able to do an experiment?
> 
> Generate your *.tex, search for placement={H} and try replacements by just processing the LaTeX? Look for anything unusual with placement or numbering? Then we can go from there.
> 
@rbeezer Sorry for the delay.  For some reason this message was sucked into a machine I left at home.

First, it is important to realize my setup.  I keep the directory into which I pull from GitHub separate from where I keep the source to the book.  I then copy the folders over to there, including the xsl folder.  The reason I do this is because I have made certain customizations (Exploration -> Homework in particular).  Probably not optimal, but I tend to focus more on content that the infrastructure.  I know I should stash, etc, but I have never quite gotten the hang of that.  My apologies for that.

What I did was a fresh pull, and copied most of the subdirectories (xsl, etc) over.  I know at least some of that worked, because my “Homework” is now labeled “Exploration”.

When I build the book with 

script/mbx -vv -c youtube -f jpg -d images/ LAFF-On-PfHP.xml
xsltproc --stringparam latex.sides "two" --stringparam debug.chapter.start '0' --stringparam latex.font.size 11pt --xinclude  xsl/mathbook-latex.xsl   LAFF-On-PfHP.xml
pdflatex  LAFF-On-PfHP.tex

Not having changed anything in that “.tex” file, it appears the book comes out identical to before.  No funny business.  However, realize that this is a manuscript largely devoid of theorems etc. so perhaps it is hard to tell what might have gone wrong.

It does not appear that figures are floating.

My assumption is that because placement={H}, this is what you intended to happen.

**Comment by mitchkeller** [comment]
Bringing @Alex-Jordan's message from pretext-support over here to add my VND464

> I don't think anyone is misunderstanding [numbering of figures in LaTeX]. 
> 
> The issue is like when you have a print copy, and you are in Chapter 12,
> and you have a reference to Figure 5.8 (say, from chapter 12) and you 
> need to flip pages to go look at that. In many math books, Figures are 
> numbered with a separate counter from Theorems, Examples, etc. To the 
> orderly mind of many mathematicians, this is a good thing. It means that if 
> there is a Figure 5.6 and a Figure 5.8, there must have been a Figure 5.7.

True, and this is probably part of why I feel so strongly about not wanting FIGURE-LIKE inside solutions and answers. Publishers have lots of latitude to suppress or relocate these items, and I would find it incredibly annoying to have skips in the sequence of numbers.

> But it makes it harder to actually find Figure 5.8. If Figures are sparse, 
> Figure 5.7 might be 30 pages earlier. You may be flipping for a while until 
> you land on some Figure that will then be a signal to either continue flipping 
> forward or backward. In the meantime, you are probably seeing things like 
> Corollary 5.6 that may mislead you, because as a student you are unaware 
> this is on a separate counter.
>
> PreTeXt numbers all these things on the same counter (by default) so that 
> helpful way point numbers will not be sparse. You will be flipping and see some 
> number quickly that signals you to go forward or backward. When you see 
> Thing 5.7, no matter what "Thing" is, you know to flip forward. And you know
> that Figure 5.8 is very close.

I think this is definitely an area where knowing the audience makes sense. With a project like ORCCA, minimizing the number of counters makes sense. This is probably also the case with Active Calculus. For Applied Combinatorics, I'm less bothered in part because we have a bunch of figures and in part because the audience is more mathematically mature.

> So now we get to floating. If Figure 5.8 floats past Example 5.9, then the way
> point mechanism is broken. It will still be labeled Figure 5.8, because as Mitch 
> says, that has to do with its position in the source. But a reader looking for it 
> who lands on Example 5.9 will start flipping in the wrong direction.

I would be interested in some actual usability studies on something like this, because I'm not really convinced that readers would be so terribly befuddled that they'd be flipping around an unable to find things.
 
> There is already an option to number &FIGURE-LIKE (figure|table|listing|list) 
> on a separate counter from all the other things, set in docinfo/numbering/figures.

I think I missed when this was announced.

> If that is your choice, you are accepting the two-counter system, and you hope 
> your readers don't read way points as I outlined above. If you are using the two 
> counters, (my opinion) it could be reasonable to let thee things float. I think it 
> should be all four things though, not just a subset. 

Yes, it should definitely be all four things.

> And I have a question because I don't know LaTeX floating so well: Can floats float past another 
> float? E.g. can Figure 5.8 end up later than Figure 5.9?

No, it cannot. LaTeX basically builds up a queue of floating things and forces them out one-by-one as it finds space for them. The catastrophic thing that can happen is that it gets so many deferred figures that it forces them all to the end of the section or chapter. Generally one then has to really dig in and see what's causing it, and sometimes all it takes is shrinking a single figure a tiny bit and then everything is good. LaTeX's float behavior can be annoying, but personally I prefer to battle with it than some of the giant swathes of whitespace that PreTeXt can trigger by its insistence upon positioning in exactly where a float appears in the source.

One of my concerns with the conversion of nearly everything to tcolorbox involves how it might impact the ability of publishers to float things by tweaking the LaTeX afterward. I already noticed some issues with this when doing ACS last summer, as ACS has a lot of sidebyside blocks that were already being rendered using tcolorbox and so it wasn't so simple to float them on a one-off basis as it was with figure and table. I wound up giving up on floating any sidebysides because it was clearly going to take a lot of digging into the LaTeX source.

It may be instructive for @rbeezer to talk with publishers about their experiences in doing the final page layout for books that have large numbers of floats, because I'm a little worried that unless something is done to help make it easy to do the final editing to have things float where necessary, people may be dissuaded from using PreTeXt.

**Comment by rbeezer** [comment]
@rvdg - Sorry if I wasn't clear.  I was suggesting you build a TeX file the usual way, then dig into that file and hand-edit the LaTeX to try different float options.  That's often how I test new things, rather than writing a lot of XSL that eventually gets thrown out.

No matter, I built a switch, which I want to announce on `-support`.  In a few.

BTW, you can rename a block in your source, no need for any extra code.  Search the sample article for "Conundrum" and consult the output to see effect.

**Comment by rbeezer** [comment]
Premature.  Should have said:  work at 8d04b26901774acf037160cfa1072bf49a093799
