### ISSUE TITLE
Cropping images with mbx script, ghostscript makes pdfcrop overzealous

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1042]
On pretext-support, Jeremy Sylvestre says:

> Just a heads up that recent release ghostscript v9.27 seems to break pdfcrop, resulting in overzealously cropped images. Downgrading back to ghostscript v9.26 fixed things.

**Comment by jjrsylvestre** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927429
https://bugs.ghostscript.com/show_bug.cgi?id=700988
https://bugs.ghostscript.com/show_bug.cgi?id=700952
http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=06c920713e11

Turns out it was fixed in ghostscript git a couple of days before I reported it on pretext-support, will have to wait for new ghostscript release.....

**Comment by loserMcloser** [comment]
Seems to be fixed in recently released ghostscript 9.50. (Not sure why the big jump in gs version numbers, but whatever.)

Request to close this issue.

**Comment by jjrsylvestre** [comment]
_(Whoops, didn't realize I was signed in in the background to my personal account when I left a comment with content below the first time. Here it is again using my public account so you know who it's from....)_

Seems to be fixed in recently released ghostscript 9.50. (Not sure why the big jump in gs version numbers, but whatever.)

Request to close this issue.

**Comment by rbeezer** [comment]
Thanks for the follow-up!  I left a small note in The Guide about this, so people know to upgrade if they have an old version.  Not yet public.
