### ISSUE TITLE
pre in a p

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1052]
The logical structure of a "p" may have a "pre" inside it,
but currently it has to be structured as a "p" followed be a "pre"
followed by another "p".

Strikes me as parallel to a display equation inside a "p".

Examples in ref="topic-index-advice" of the Author's Guide,
soon to be Section 6.16.1

**Comment by rbeezer** [comment]
Use `cd` like you would use `md`, and then use `cline` within, like you would use `mrow`.

Looking forward to "index advice" which I almost started on myself.

**Comment by davidfarmer** [comment]
Well, my pull request will use "pre".

**Comment by rbeezer** [comment]
`pre` is definitely the easiest to use.  But I think here you've broken up some logical paragraphs.  Also, iirc, `cd` will center (the whole block, respecting indentation) in one output format, but not in the another.

I'm going to close this, since we **do** have an in-paragraph version of displayed monospace.
