### ISSUE TITLE
mention examples for referring to a division

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1070]
After nearly posting a long new issue here after Pilar W.'s very helpful exposition yesterday, I discovered there are indeed examples like this where a whole section is indexed.  I didn't know this syntax was legal:

```
        <section xml:id="section-interactive-authored">
            <title>
                <line>Interactive Elements</line>
                <line>Authored in Javascript</line>
            </title>
            <shorttitle>Interactive Elements, Authored</shorttitle>
            <idx><h>interactive elements</h><h>authored</h></idx>
            <idx><h>embedded interactive elements</h><h>authored</h></idx>
```

But I don't think this is mentioned explicitly anywhere in plain text.  Probably should be both here and in the indexing guide as examples for what to do.  Obviously fairly low priority issue.

**Comment by davidfarmer** [comment]
But in many cases index entries pointing to a section are not really what
the author intended.  So yes, this works.  But it requires some thought
and knowledge to use it properly.

We definitely need to make a few updates to the indexing advice.  Feel
free to add to this issue:
https://github.com/rbeezer/mathbook/issues/1055

Also, there is (or was) a bug that made index entries in an assemblage
point to the parent section.  Probably still "is", because the issue
is still open:
https://github.com/rbeezer/mathbook/issues/753

**Comment by kcrisman** [comment]
> But in many cases index entries pointing to a section are not really what
the author intended.  So yes, this works.  But it requires some thought
and knowledge to use it properly.

Fair enough; I guess I just wanted to make sure it was more evident.  If we think that #1055 is appropriate I can add it there.
