### ISSUE TITLE
Activity numbering customization

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1078]
Currently activities (more generally "project"s) are numbered distinctly according
to line `1020` in `mathbook-common`.

```
<xsl:variable name="b-number-project-distinct" select="true()" />
```

Editing `true()` to `false()` results in an error: these activities are given a number (since later elements are incremented approrpriately), but `NaN` is shown in place of the activity number.

![image](https://user-images.githubusercontent.com/1559632/59710796-915b3c00-91be-11e9-840b-09c42abc9dee.png)
![image](https://user-images.githubusercontent.com/1559632/59710814-9c15d100-91be-11e9-931b-ddfe5021d31b.png)

**Comment by rbeezer** [comment]
I believe I've fixed the root cause of this.  Pushed as 002c0f48cf8a104d69962b351e08446d8b409713

@StevenClontz: could you please test?  Set the boolean at line 1020 to `false()` as before and observe your output.

I'll enable this behavior as part of the new publisher configuration.  So just sit tight and keep writing source - we'll catch up soon.

Thanks for your help!

**Comment by StevenClontz** [comment]
Unfortunately, this hasn't fixed the issue on my end.

![image](https://user-images.githubusercontent.com/1559632/59978573-9f300900-9592-11e9-91c3-4ff399773bef.png)

I destroyed my old build to be safe, and rebuilt using `mathbook-html.xsl`. I still have `NaN` activities. :-/

**Comment by StevenClontz** [comment]
Looks great! (If you got a ping from my previous reply, it's because I was a dummy and forgot to pull the new commit first. 😬 )

**Comment by rbeezer** [comment]
Very good!  Thanks for checking, and for provoking this one.  We'll make a 
"publisher switch" soon.  -Rob
