### ISSUE TITLE
conclusion to "basics"

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1128]
The "basics" section is pretty user-friendly, with a nice intro at https://pretextbook.org/doc/guide/html/ch-about.html, so I recommend (but not demand) some sort of brief conclusion as well - in particular, recommending not just the rest of the guide, but the sample article as well.

**Comment by mitchkeller** [comment]
No one should ever recommend the sample article to anyone. The point of the sample article is stress testing and debugging.

With the documentation fully integrated (and plans for completing the Basics Reference including thorough and deep `xref` linking to the rest of the Guide), I'm not sure I see a need for a conclusion. Unless @kcrisman has more specifics about what a conclusion should say, I would close this issue.

**Comment by rbeezer** [comment]
On 7/2/19 2:34 PM, Mitchel T. Keller wrote:
> No one should ever recommend the sample article to anyone. The point of the 
> sample article is stress testing and debugging.

I agree - that is where we are going.  It was stopgap documentation, and still 
is for features-in-progress.

**Comment by kcrisman** [comment]
> Unless @kcrisman has more specifics about what a conclusion should say, I would close this issue.

It should say "here is where your next steps are".  If it is truly supposed to be a welcoming introduction of basics to newcomers, it should read like that.  This can be brief; links to a few often-requested questions, or to the other portions of the guide, would probably suffice.  But the way the html version looks now, you go straight from some brief information about quotation marks and a few words about modular source to the very different publisher's guide.  That doesn't sound too welcoming to me.

-------

OT sample article discussion:

> I agree - that is where we are going.  It was stopgap documentation, and still
is for features-in-progress.

That's nice and all, but in reality I very, **very** often find this is the only true documentation for stuff I need to know.  (For instance, what is important in `<docinfo>`?  The schema won't tell you.)

Even the Author's Guide, if its current scope in non-starred sections is an indication, will be _far_ from comprehensive enough.  As an analogy, consider the Sage documentation.  The introductory sections for many parts are fine for the most beginning purposes, but one really has to see every submethod's documentation in order to know exactly how to use it - and there, having every branch demonstrated as well as tested is stressed.

I don't mind if we don't want people to see the sample article.  But then we need a replacement for it for practical purposes, and the Author's Guide is not even close to that yet.  So we need to acknowledge that.  Maybe the guide isn't the right place, but it's unavoidable one way or another.

**Comment by mitchkeller** [comment]
> > Unless @kcrisman has more specifics about what a conclusion should say, I would close this issue.
> 
> It should say "here is where your next steps are". If it is truly supposed to be a welcoming introduction of basics to newcomers, it should read like that. This can be brief; links to a few often-requested questions, or to the other portions of the guide, would probably suffice. But the way the html version looks now, you go straight from some brief information about quotation marks and a few words about modular source to the very different publisher's guide. That doesn't sound too welcoming to me.

I don't view the Basics Reference as something anyone should read in order. It's a quick reference that you go to when you need template code for a particular tag. If you want to learn more about the philosophy and features of PreTeXt, you read the Author's Guide portion of The Guide. When you have a good idea of what you want but need syntax, you use the Basics Reference. Thus, there are no "next steps" because one does not "finish" reading the Basics Reference. Perhaps when this was going to be a standalone reference some concluding words would have been in order, but now everything the reader could be interested in is right there in the table of contents at the left. In fact, to get to the Basics Reference, they had to jump past the Author's Guide.

> 
> OT sample article discussion:
> 
> > I agree - that is where we are going.  It was stopgap documentation, and still
> > is for features-in-progress.
> 
> That's nice and all, but in reality I very, **very** often find this is the only true documentation for stuff I need to know. (For instance, what is important in `<docinfo>`? The schema won't tell you.)
> 
> Even the Author's Guide, if its current scope in non-starred sections is an indication, will be _far_ from comprehensive enough. As an analogy, consider the Sage documentation. The introductory sections for many parts are fine for the most beginning purposes, but one really has to see every submethod's documentation in order to know exactly how to use it - and there, having every branch demonstrated as well as tested is stressed.
> 
> I don't mind if we don't want people to see the sample article. But then we need a replacement for it for practical purposes, and the Author's Guide is not even close to that yet. So we need to acknowledge that. Maybe the guide isn't the right place, but it's unavoidable one way or another.

We know the existing documentation isn't enough, and we talked extensively in Portland about a roadmap. There is also a documentation steering committee, from which you will be hearing very soon. The first step was to assemble The Guide and be more proactive about calling for contributions. One proposal for the Basics Reference involves having simple, intermediate, and complicated examples for each of the elements discussed. (Some likely won't lend themselves to complicated, and that's fine.) We need people to contribute those examples, however (once the call is issued). If there are things that you feel are missing from the outline of the Author's Guide, then propose the additions. We can send people to the sample article on the Google groups if they ask a question that we know is only/best answered there. If the official documentation sends casual users into that rabbit hole, they may run away in terror.

**Comment by kcrisman** [comment]
> When you have a good idea of what you want but need syntax, you use the Basics Reference.

Oh, that was definitely not how I was interpreting it.  I don't know if it will fulfill this role yet or not.

> If the official documentation sends casual users into that rabbit hole, they may run away in terror.

Sure.

If this was all just a lengthy discussion on whether to close this issue, I don't care THAT much.  I admit defeat.  But it seems like we are at times going out of the way to be completely done with a lot of other stuff before providing usable documentation to those who haven't studied the same article in depth.
