### ISSUE TITLE
task answers visible even with exercise.inline.answer no

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1527]
In an inline `exercise/webwork-reps/static` with `tasks`, even with `--stringparam exercise.inline.answer no`, the task answers are still visible in HTML output. Have not tested if this is specific to tasks in webwork or an issue with tasks in general.

**Comment by rbeezer** [comment]
Not just WeBWorK.  Sample article, Checkpoint 4.10 will illustrate this bug.

Exercise 4.10: A very structured exercise 
https://pretextbook.org/examples/sample-article/html/interesting-corollary.html#exercise-structured

Has `task/answer` and for HTML build, the switch `-stringparam exercise.inline.answer no` does not seem to remove them.  Does not appear to be due to recent work on WW tasks.

**Comment by rbeezer** [comment]
Getting warm - the `project.answer` stringparam **is** effective for a `answer` on a `task` in an inline exercise.  And there appears to be some breakdowns in passing the switches into the various components of an `exercise`...

**Comment by rbeezer** [comment]
Should be fixed at a37361de9826f7fe5ce376d2b8f4d6b708d5b465.  Author-supplied switches for PROJECT-LIKE were controlling the visibility of **all** task.  Now dependent on the six scenarios where a `task` might occur.

Can you report the next time you are using this?

Do you think a warning is necessary on `-announce`?  "This was broken.  Fixed now, which may result in changes."?
