### ISSUE TITLE
Guide: Should the "publisher file" be called a "publication file"?

### ISSUE THREAD

**Issue by oscarlevin** [rbeezer/mathbook#1578]
In the CLI, we call it a publication file, since its root element is `<publication>`, and we build `publication/publication.ptx` as the template publication, eh, publisher file.  

It's a file for a publisher to use, but different publisher files are likely used by the same publisher to make different publications.

I'm happy to make the change if it is agreeable.

**Comment by rbeezer** [comment]
Well, I did make a mess of this one.  There needs to be one stringparam, at least, to route this filename into the XSL.  And there is lots of fancy footwork in  pretext.py to make sure it is not duplicated in the -x argument.  At least a lot of the internal Python uses "pub_file".

No matter what we call it, we have a root element and a stringparam that are different.  Changing either will be painful.  If documentation changed to "publication file" do you think the author-facing aspects can remain as-is?  I guess I do like "publisher file" since it reminds people of their role.  And I'm now thinking we could gracefully translate the root element.

Off-duty almost all weekend.

**Comment by oscarlevin** [comment]
My instinct is to use "publication file" in the documentation, and leave everything else as is.  The CLI has this help text: 

`  -p, --publication PATH          Path to publication *.ptx file`

I suppose for consistency, allowing `--publication` in addition to `--publisher` in pretext/pretext.py for the developers would be a nice touch (I know Click allows multiple flags to do the same thing; I assume this wouldn't be difficult with the setup you have).  

I agree that it is a nice reminder for the role distinction.  But there again, what sort of files would a publisher have?  Publication files.

**Comment by rbeezer** [comment]
I've been using `publication` more and more often.  So now we have a mish-mash.  Maybe as part of some massive documentation review, the most egregious instances can change?  Like chapter tittles.

**Comment by rbeezer** [comment]
You can have as many versions of a flag as you want.  We have two right now for most, a `-x` form and a `--xyz` form.

https://stackoverflow.com/questions/50896992/argparse-add-argument-alias

https://docs.python.org/3.6/library/argparse.html#the-add-argument-method

**Comment by rbeezer** [comment]
Added `--publication` as another switch and noted `--publisher` as deprecated.  Then had to change the `publisher_file` variable to `publication_file` since the name shows up in the automaticlly-constructed `-h` help.  All in the user interface, the CLI should not notice at all.

And then made some small changes to the Guide just for `pretext/pretext`, and resisted the further slippery slope.

More to do, but I'm going to close this, since the rest can happen as needed or while in the vicinity.

The `publisher` stringparam would be a dangerous job, but I think that is largely hidden now.

Python: 25e8de20809506f5310b1baa91203dafbdf344ed

Guide: 323af4692579c3343a021cb292d17dcc171f0eea

**Comment by rbeezer** [comment]
Brute-force changes in the Guide at 1b17192e3e50047327854254def2cf1448539064

Public on next website refesh.  We still have an (internal) stringparam `publisher` that would be used with `xsltproc`.  Gets tricky in core Python routimes, so I'm not brave enough to bear the fallout from messing that one up.
