### ISSUE TITLE
Warn about backticks

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1620]
Backticks, or maybe just double backticks, in the HTML cause MathJax to choke.

If these are in the PreTeXt source, ` ``like this'' `, an error or a warning should the given.

Not sure if those ever have a legitimate purpose in PreTeXt source?

**Comment by davidfarmer** [comment]
I think the problem is triggering ASCIIMath in MathJax.

**Comment by davidfarmer** [comment]
Now I think the problem is that MathJax should only be configured to look for AsciiMath in
certain places, such as the answers to reading questions.

This problem has probably existed since we started using MathJax3.  Nothing wrong with
MathJax3, but when we stitched, we did not set it up properly.  Problems in the sample article
backticks paragraph, for example:

https://pretextbook.org/examples/sample-article/html/text-in-paragraphs.html#p-380

**Comment by rbeezer** [comment]
Because slash-paren is two characters, we "break" it by putting a zero-width space in the middle for it's (unlikely) occurrence in regular text.

Can we configure MathJax to do asciimath based on two characters and maybe pre-process the source to this form.  What about the actual HTML tags that signal math?  Why are we fighting ad-hoc markup?

Certainly something here I'm not understanding correctly.

**Comment by Alex-Jordan** [comment]
>  Because slash-paren is two characters, we "break" it by putting a zero-width space in the middle for it's (unlikely) occurrence in regular text.

Side note: This can drive a person nuts. Copy-paste and "why won't it work?!?!?"

If a character is &#'-ed (like `\` to `&#92;`) does that block MathJax? Or is it too late once the browser has turned it back into `\`?

**Comment by Alex-Jordan** [comment]
Here is something to consider:
https://spot.pcc.edu/~ajordan/temp/mathjaxtest.html

If you wrap a span around each MathJax delimiter, that prevents MathJax from latching onto it.

**Comment by davidfarmer** [comment]
1) I added "processme" to the answer javascript, so that can be tested.

2) The WeBWorK javascript also contains the MathJax configuration,
    so that is another place to update once we know the new setup.

3) I am in the midst of a CSS upgrade (from 0.31 to 0.4) and am
    thinking we also need a JavaScript upgrade.

4) Doesn't Alex's recent work on inline math nobreak make it easy to
    wrap inline math in a .processme?

**Comment by rbeezer** [comment]
Built AATA:

* Set the "platform/@host" so that logins are enabled, JS included, etc.

* Used the ignoreme/processme experimental MJ 3 configuration.

* Logged in, answered a reading question with "$x^2$".  Preview changes it to "\(x^2\)" so *something* happens.  But not being rendered as math.

https://pretextbook.org/beta/2021-10-13-reading-answers/reading-questions-1.html

(reading-questions-2 is there also, but nothing else)

Some ASCIIMath errors in the console, not sure if that is related.  Noob that I am, I could even see "processme" in a plce that looked reasonable.  I dropped "has_am" from the PTX MJ configuration in the above example, got a similar experience before trying that.

Rob

**Comment by davidfarmer** [comment]
Apparently I had never updated the reading questions code to
work with MathJax3.  I just did, and those seem to work for me.

**Comment by rbeezer** [comment]
Backticks outside of math contexts will not be seen by MathJax now, with d5ef68ffa5ab5262a4a4f07258596ccb9f2f9790

So no need for warnings, and authors can continue to use their keyboards to make whatever nasty strings they wish.
