### ISSUE TITLE
RevealJS: macros must be in `<div class="reveal">`

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1648]
https://github.com/rbeezer/mathbook/blob/8cf83ac42115c1433f4322a7218c9ecfaab573bd/xsl/pretext-revealjs.xsl#L179

Move this into `<div class="reveal">` - apparently the way MathJax is currently configured it only processes math in there.

**Comment by davidfarmer** [comment]
There also is the

processHtmlClass

option of MathJax, which could be adjusted.

https://github.com/rbeezer/mathbook/blob/8cf83ac42115c1433f4322a7218c9ecfaab573bd/xsl/pretext-html.xsl#L11851

**Comment by rbeezer** [comment]
Fixed at 9e9ad7827e8bbf28e7d8b5b021bddc121a368fcc.  Thanks @StevenClontz  for the catch and diagnosis.  Confirmed in the sample-slideshow and fixed for that case.

@davidfarmer: RevealJS is stuck on MJ 2.x.  So we can't use the `ProcessHTML` device, and fortunately, all our `span` around bits of LaTeX are not a hindrance either.  When investigating this months ago, I got hints that RevealJS would rather move to KaTeX, or similar, rather than battle an upgrade?

Maybe the day will come when we need to roll our own use of MJ in these situations.  The plug-in/extension provided by Reveal does not do much, iirc, it just enables an online connection with a MathJax CDN.  It does not allow you to archive, or present offline, a presentation, despite appearances.
