### ISSUE TITLE
Incorrect namespace on generated html elements

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/mathbook#1652]
When `html` is generated via `pretext-html.xsl`, it appears that `xmlns:svg="http://www.w3.org/2000/svg"` is added to several HTML tags...For example, in the minimal example,

```html
<section xmlns:svg="http://www.w3.org/2000/svg" class="section" id="section-interesting"><h2 class="heading hide-type">
<span class="type">Section</span> <span class="codenumber">2</span> <span class="title">A Bit More Interesting</span>...
```

shows up. I believe `xmlns` should not show up on any HTML elements.

**Comment by rbeezer** [comment]
Yes, I'm all too aware of this one.  More than **several**.  ;-)   We have one or two SVG graphics in the XSL code (like a big red play button we put over videos), so we have to get the namespace right there.  I think.  The XSL serializer is also out of our control (that's a feature, I think), and these seem to come and go.  I just made some seemingly unrelated changes this afternoon, and a bunch of new ones popped up.

I should knuckle-down and experiment.  I've learned a few new things on this front since the last time I attacked this one.  We allow HTML elements in the source of selected parts of an `interactive` so there is something of an inverse problem there as well  (identifying HTML elements v. PreTeXt elements in source).

**Comment by rbeezer** [comment]
OK, I think this slipped in with f19c8824612b1213bae052c642cfad29dbe09528

I know what to do about it, but want to test that (derived) EPUB with SVG math will still validate.

Thanks for the push.  I'll close once confirmed.

**Comment by rbeezer** [comment]
Necessary change at c34b5313fb71ca185d1b0bef2294b15c83584aad, followed by some other related improvements.  HTML (and EPUB) output should be whole lot cleaner now (though we still can't control indentation).

Thanks again for recognizing that this was a mess.

Rob
