### ISSUE TITLE
adding \leavevmode before lists in tex

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#166]
As discussed here: http://tex.stackexchange.com/questions/73741/enumerate-alignment-problem-in-theorem-environment

An undesirable thing happens when a list is the very first thing in a theorem environment. I discovered this with webwork exercises. Remember that an `<exercise>` is a theorem as far as latex is concerned.

I put `\leavevmode` at the beginning of lists in `mathbook-latex.xsl` (as the answer at the link says), and I see no bad consequences in how the sample article comes out. Consider putting this in?

**Comment by davidfarmer** [comment]
My answer to that StackExchange question would have been:

    The editor of the journal should tell you to insert
    the words "We have:" at the start of the Theorem.
    So this is a non-issue.

I gather that this is an actual issue for MBX, because,
apparently, it is okay style for an exercise to only contain
a list.

The \leavevmode seems fine to me, since it is a purely
back-end fix and the author doesn't need to know anything
about it.  I assume it will only be added when it is
actually needed?  I.E., only when the first think in a
"theorem" is a list?

Does anything need to be done in the HTML?

**Comment by Alex-Jordan** [comment]
I haven't checked what "regular" MBX HTML output looks like in this case. MBX HTML WeBWorK output looks fine, but that has a WeBWorK cell wrapping the list. 

Only doing it when a list comes first sounds good.

**Comment by rbeezer** [comment]
And should be easy to accomplish only as needed.  Lists, their labels, and numbers for items all deserve a good hard look, so this could naturally be part of that work.  Such as with #140

**Comment by Alex-Jordan** [comment]
Perhaps this is more of a general issue for when the first node of an exercise (or other theorem-like thing) is not text. In CLM I just noticed an exercise (that's part of an exercisegroup) that begins with a table. The table is middle-aligned with the exercise number instead of top-aligned, which I think would be better. (For now I'm going to have my script do post-processing substitutions for this.)

**Comment by rbeezer** [comment]
I agree with David about style, but since authors cannot easily patch up their LaTeX, we should help defend against this nonsense.

At cc5cb5f6 I've added a few `\leavevmode` prior to each outer-most list and prior to each table.  Not sure if I need to defend `tabular` or not, and do not want to mess up `side-by-side` in the process.

@Alex-Jordan : would you mind taking down your shields and see if (a) this is successful, and (b) if I missed anything?

I was able to easily build an example of each problem for the sample article and the changes correct both of them.

**Comment by rbeezer** [comment]
This appears to be behaving itself, and has been extended/generalized at #191, so I am closing it.  @Alex-Jordan: you can take out your additions now, I think.
