### ISSUE TITLE
Equivalent of <pre> tag

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#21]
For now, workaround is

            <program>
                <input>
                stuff
                </input>
            </program>

at least I think that should work, but maybe that's not ideal.

**Comment by rbeezer** [comment]
Right.  `<c>` works for small inline snippets, but I really need something for large blocks (w/ carriage returns) that is not as cumbersome as `<program>`, which is meant for programming languages listings.  I do think your workaround is the best suggestion now.

What do you think of `<code>`, which would get sanitized like `<input>` does?  (Preserve line breaks, preserve indentation, etc).  Or maybe just recycle `<pre>`?

**Comment by davidfarmer** [comment]
The other day I learned of the term "tag abuse", which is when you use
a tag merely for the side-effect of having its contents appear with the
desired visual appearance.

Since (presumably!) <code> should contain actual code, it would be bad
to have the <code> as the generic preformatting tag.  Since we need
a generic preformatting tag, it makes sense to recycle <pre>.

I see an analogy with <term> and <emph>.

What to do before we have both a <code> and a <pre> tag?  I think the
suggestion of using <program><input> is a good one, because it is
obviously tag abuse, intended to be temporary as we develop the standards,
and can be fixed later.

**Comment by rbeezer** [comment]
On 16/01/2015 14:20, davidfarmer wrote:
> I see an analogy with <term> and <emph>.

So if I understand right, it would be <q>tag abuse</q> if I were to use <em> on 
a defined term?  Because I am simply using the tag to gain the visual formatting 
that I think a defined term should have?  So we have <term> to prevent tag 
abuse?  And need <pre> to prevent more.

Is it abusive to *have* an <em> tag in the first place?  I would argue not, but 
on first reading I thought this might be what you meant by "use
a tag merely for the side-effect of having its contents appear with the
desired visual appearance."

Rob

**Comment by davidfarmer** [comment]
Yes to your first question, and that is probably the most
common example of tag abuse.  (Or maybe it is <i> for <em>.)
We need <em> because sometimes *emphasis* is just <q>emphasis</q>.

But we need to train people to use the semantic markup when it is
available, and alert us to cases where we may need a new tag.

Let's hope nobody thinks to suggest <python>, <perl>, and <C++>
tags in place of the generic <code> tag!   (You may want an
optional language="python" attribute to <code>.)

**Comment by rbeezer** [comment]
<program> supports a plethora of language="".

LaTeX output uses the listings package and HTML uses Google's CodePrettifier, 
both to achieve syntax highlighting.  The <input> and <output> have obvious 
uses.  So the intent is that language-specific code goes in <program>.

Maybe <code> should be like a block-level version of the inline <c>.  That would 
be my first thought.  And <pre> would be more generic.

I am giving my students here at AIMS lots of "stuff" they can cut/paste out of 
an assignment into Sage worksheets.  Mostly entries of semi-big matrices (list 
of lists of numbers).  Not program statements, perhaps code, more 
computer-specific than just <pre>.

Suppose you provided a small data set to a reader.  20 rows, 6 numbers to a row. 
  Formatted so it could be cut/paste without loss (eg, minus signs are not some 
Unicode dash, as sometimes happens in PDFs).  What would you wrap that in?

Rob

**Comment by kcrisman** [comment]
Maybe <code> should replace <program>; not all code is an actual program.  For instance, it could be a non-functioning snippet.

**Comment by davidfarmer** [comment]
I think we need to take this discussion to the mailing list so more people can comment.
A particular concern is missed use cases.

**Comment by kcrisman** [comment]
If you do have that discussion, is there a tag for "comment" as well?  Perhaps something that would drop down a knowl ... that is actually what I have been using the pre tag for.

**Comment by rbeezer** [comment]
I have implemeted and pushed a `<pre>` element.  I really needed it the past three weeks at AIMS so was anxious to put it in place.

KDC - I'm uncertain about your request for a "comment" tag.  Comment on something in particular, or would the remark tag be too heavy (gets a number)?  Remarks will be knowlizable eventually.  I'm thinking maybe we already had that discussion?  Anyway, please open a new issue for "comment" as I am going to close this one now.
