### ISSUE TITLE
CSS issue with first p in paragraphs

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#221]
Here is a copy of the Author Guide:
http://spot.pcc.edu/~ajordan/MBXAuthorGuide/introduction-to-source-formatting.html

There is an issue with the CSS for `paragraphs/p` that you can see (at least, I can see it in Firefox 45.0.1 on Mac El Capitan). The first `p` in a paragraphs has no vertical skip to the second paragraph, while subsequent `p`s do have a skip that follows them. The "Learn to Use Your Editor" paragraphs is one such example.

When I examine the active CSS, the first `p` has `display: inline` which I assume is so that the title of the paragraphs will be inline with the first `p`. Later `p`s appear to have `display` left as default.

**Comment by davidfarmer** [comment]
Dear Alex,

Good catch.  It was slightly tricky to fix.

And this is a great example of why it is good to provide an actual online
sample, instead of merely describing the problem.

Paragraph spacing is controlled by margin-bottom on a p, but the
inline setting in that case removed the bottom margin.  So I added
this to the CSS:

.mathbook-content .paragraphs .heading + p + p {
     margin-top: 1.25em;
}

which adds space above the second p in a paragraphs.

But then I saw that lower down on that page there is a similar
problem between the "Revision Control" and "Whitespace" paragraphs.
There is only one p in "Revision Control" so the above CSS does not
apply.

Logic like "add space after a paragraphs if it contains only
one p" is pretty much impossible in CSS (for me, anyway).

So it looks like we just want to add margin-bottom to that first p,
but you can't do that because it has been set to inline, and you
can't add top or bottom margins to inline elements, because that
would mess up the "flow".

So I did this:

.mathbook-content .paragraphs .heading + p:after {
     content: "";
     display: block;
     margin-bottom: 1.25em;
}

Reload the page to see it.

If someone has a better way, I'd be happy to do it differently.

Regards,

David

**Comment by rbeezer** [comment]
@Alex-Jordan  Yes, thanks for catching this one. I think I had noticed this behavior, but never sat down to debug exactly what the scenario was.

@davidfarmer Thanks for the fix!  Now you are beginning to think in XSL terms.  The cases might drive you crazy.  Do I see slightly greater "inter-line" spacing (the leading) in paragraphs with the inline heading, versus paragraphs without?

**Comment by davidfarmer** [comment]
There is a CSS weirdness with line-height, which traditionally refers
the distance between lines in text.  It means something different for
a p styled inline and a p styled as block.  So even though it is set
to 1.25em in both cases, it ignores it in the inline case.

Seems impossible to fix without changing the html.

The following would work.  Let me know if you think it is reasonable.

In the html of a paragraphs, instead of writing

<article class="paragraphs">
<h5 class="heading">
<span class="title">Revision Control</span>
</h5>
<p>
first paragraph
</p>

we write

<article class="paragraphs">
<p>
<span class="title">Revision Control</span>
first paragraph text
</p>

It demotes the heading of a paragraphs to a .title, but I'm probably
okay with that because it isn't a real heading.

Another option would be

<article class="paragraphs">
<p>
<h5 class="heading">
<span class="title">Revision Control</span>
</h5>
first paragraph
</p>

where only the location of the opening p tag moved.  (Style the h5 as
inline and it looks like you want.)

All the options I can think of have the title put inside the first p
of a paragraphs, so we don't need to style that p as inline.

**Comment by davidfarmer** [comment]
I retract that second option  The browser ignores the styling and adds a closing p tag
before the h5, so the source you send can't be styled as you might wish.

The CSS is already in place for the first option (but I may not have covered all cases).

**Comment by rbeezer** [comment]
Dear David,

I can recognize the first "p" in a "paragraphs" and I can insert the title into 
it.  And it looks good.  This assumes that the first chunk of content in a 
"paragraphs" is really a "p".  Right now, the DTD does not have that restriction 
(I'm OK with introducing it, though.)

You can see fixed "paragraphs" in Section 4.5. (You'll see stray debugging XX 
throughout at paragraphs titles).

http://mathbook.pugetsound.edu/sample-article/section-4.html

Bigger problem - we have lots of inline titles/headings like this. See, for 
example, Principle 4.4.

I think Theorems, etc have this problem, too, but we didn't always recognize it 
with text set as italic.

Anyway, it is hard to just stuff a title into the first element of a structure, 
without knowing what that element is.  Which is the same problem you have with 
CSS.  Usually a "p", but I don't think it always has to be?  An exercise might 
lead with a table, for example.

Question:  Are there any situations I can recognize with XSL (first child, last 
child, etc) that would allow me to place class attributes on the elements that 
would aid things on the HTML/CSS side?

Otherwise, if we need to have a block first, I'll have a fair amount of work to 
do to get all the "h5" stuff into the first block, and will need to enforce 
assumptions on the nature of that first block via the DTD.

Rob

**Comment by davidfarmer** [comment]
I looked at the html and css documentation pretty carefully, and now am
pretty sure that we must avoid styling a p as inline.

So for theorems/remarks/etc, if the first content is a p, then we need to
have the title inside that p, in a span with class "title".

Is it difficult to put the title inside the first element when that first element
is a p, but not otherwise?

Maybe let's list all the possibilities before making big changes.

**Comment by rbeezer** [comment]
On 04/06/2016 04:03 PM, davidfarmer wrote:
> I looked at the html and css documentation pretty carefully, and now am
> pretty sure that we must avoid styling a p as inline.

Dang. ;-)  I'd pretty much come to the same conclusion.

> So for theorems/remarks/etc, if the first content is a p, then we need to
> have the title inside that p, in a span with class "title".
>
> Is it difficult to put the title inside the first element when that first element
> is a p, but not otherwise?

Not exactly, you need to write a template for each possibility that could be 
first.  Or at least that was the way I was doing it via a matching.  It might be 
better/easier to condition on the right situation(s).

> Maybe let's list all the possibilities before making big changes.

Yes, no matter what, that is a good idea.  I think many of them will involve a 
"statement", which could be beneficial.

Do you think this could wait until after the workshop?  It'll take some time to 
do right.  Is it possible to make the CSS tolerable for the old way and we just 
live with it for a few more weeks?

Rob

**Comment by davidfarmer** [comment]
Most of what I wrote on this issue is no longer applicable because of fundamental
changes in the HTML and CSS.  So this issue can be closed.  If any of the symptoms persist,
open a new issue.

**Comment by Alex-Jordan** [comment]
David said we can close this, so I'm closing it.
