### ISSUE TITLE
Add <part> on refactor of chunking code

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#25]
For kcrisman and kkedlaya.

Design question: should the distinction between a book and an article simply be based on which sections are present?

**Comment by kcrisman** [comment]
Maybe.  My real sense is that the names of subitems should be 100% configurable.  What's the current state?

**Comment by davidfarmer** [comment]
I can think of two reasonable ways to handle this:

1) Use exactly the standard LaTeX divisions, starting with "part" and going down to "subsubsection."
Have a small number options for chunking these in standard ways.

2) Allow an arbitrary number of levels in the hierarchy, with (almost) arbitrary names.  Allow an option
for arbitrary chunking at the output file level, and configurable depth in the TOC, and configurable
expand/collapse options in the TOC.

The first option is reasonable because you can do it once and forget about it, and 95 percent of
the people will find it satisfactory.  The second option has a possibly large amount of one-time work,
probably by one person.  Anything between those options seems like asking for trouble.

I have been thinking about the second option for SL2X, and if I think about it enough I will probably
conclude that I can do it and it maybe isn't really that hard.  But I don't know enough about XSLT
to guess if the same is true for MBX.

**Comment by rbeezer** [comment]
I thought seriously about allowing generic <section> to many depths.  It has its 
advantages.  But it gets very confusing when you author.  I've got nested lists 
going lately, and it can be a real rat's nest sometimes if you lose your place. 
  With named subdivisions, and a good editor (tag-completion, tag-matching), it 
is hard to make syntax errors (and I rarely do now).  I could say more, but I 
think  part/chapter/section/subsection/subsubsection  is superior.

I am definitely shooting for 95% satisfaction resulting in 100% ease-of-use. 
Structure should be an MBX core feature and should not be configurable or 
customizable.  The presentation of that structuure can be.  So I like (1) and it 
would be a huge effort/chore to switch now and would break many, may things.  As 
is, chunking can happen easily at any level and it is totally generic/general. 
So there is no need to limit it.

Rob

**Comment by davidfarmer** [comment]
I was heading to that same decision for SL2X, until this thread which made
me start thinking about allowing more general structures.  I am happy to
go back to my original plan.

Let me know when you will start implementing "part" because I'll do the
SL2X work in parallel.  I am not in a hurry.

Also, from the author's perspective there is one more level: "paragraph",
which can be thought of as a subsubsubsection* that you can put anywhere.

**Comment by kcrisman** [comment]
> Also, from the author's perspective there is one more level: "paragraph",
which can be thought of as a subsubsubsection* that you can put anywhere.

Interesting - elsewhere it says that this is the same as `<p>`, but maybe that is not quite the case?  (Are they numbered, for instance?)

> Structure should be an MBX core feature and should not be configurable or
customizable.  The presentation of that structuure can be.

Examples of this would be really really helpful to see.  Maybe I just have to look at the source of some of the other books - just kind of a drag to search through them looking for exactly what I'm looking for.

Anyway, sounds like this confirms that adding `<part>` is the way to go on this ticket.

**Comment by davidfarmer** [comment]
A <paragraph> contains a <title> and one or more <p>s.

That title is typically typeset an bold-face words at the start of
the first <p>, in line with the first actual sentence of that paragraph,
not numbered.

**Comment by rbeezer** [comment]
Exactly.  No numbers, no chunking at this depth, can sit inside of most any 
other subdivision.  It is a kind of light-weight section.  Modeled after LaTeX's 
\paragraph (which technically sits below subsubsection, and above 
subsubparagraph, but is not not numbered by default.)  I use it frequently for 
shorter documents.

Rob

**Comment by rbeezer** [comment]
On 20/01/2015 16:52, kcrisman wrote:
>     Also, from the author's perspective there is one more level: "paragraph",
>     which can be thought of as a subsubsubsection* that you can put anywhere.
>
> Interesting - elsewhere it says that this is the same as |<p>|, but maybe that
> is not quite the case? (Are they numbered, for instance?)
>
>     Structure should be an MBX core feature and should not be configurable or
>     customizable. The presentation of that structuure can be.
>
> Examples of this would be really really helpful to see. Maybe I just have to
> look at the source of some of the other books - just kind of a drag to search
> through them looking for exactly what I'm looking for.

What is "this"?

<paragraph> or "presentation of structure"?

**Comment by kcrisman** [comment]
> Exactly.  No numbers, no chunking at this depth, can sit inside of most any
other subdivision.  It is a kind of light-weight section. 

Perfect, this is actually what I was looking for for some stuff, maybe for some of my current subsubsections.

> What is "this"?  <paragraph> or "presentation of structure"?

Presentations of structure.  Like how to use css or something to (easily) customize presentation of things.  See https://groups.google.com/forum/#!topic/mathbook-xml-support/E7QTemrZybo where the conversation has already begun.

**Comment by kcrisman** [comment]
By the way, in the localization file there is already
```
 <localization string-id='part'><xsl:text>Part</xsl:text></localization>
```
as well as a `<volume>` element.  Are those relevant?  (Maybe you already implemented it and just forgot?)

**Comment by rbeezer** [comment]
Not implemented.  Planning ahead while I had translators.

Rob

**Comment by kcrisman** [comment]
Understood, makes sense.

**Comment by kcrisman** [comment]
Since you've now implemented poems (which I'm sure I'll find a way to get in my project), and since I plan to work on using this again off and on for the next several weeks, wondering whether this particular item is in the near future.

**Comment by rbeezer** [comment]
Now have `<part>` (roughly) at 917273b7.  Two caveats:

1.  Their numbers should be Roman, but are now Arabic in HTML.  Easy to fix when I do the hard job of fixing up numbering generally.
2.  Chapters numbers are reset for each part.  This contradicts out-of-the-box LaTeX.  But it was easiest to change LaTeX to sync with HTML.  This will be configurable at #116.
