### ISSUE TITLE
html index peculiarities

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#283]
Currently what that looks like is a little weird: 
- I get an index after Notation, but on the main backmatter page it is just a small blank clickable line. (This is known at https://groups.google.com/d/msg/mathbook-xml-support/7tUsaTGCZuM/c3s3_DW_BQAJ)
- The knowls do not have numbers (perhaps this is to-be-implemented)
- The entries are case-sensitive!  This does _not_ happen in the pdf latex version.
  
  B
  Bachet equation   Paragraph
  Bezout identity  Definition
  
  C
  Chinese Remainder Theorem    Theorem
  
  ... [continuing]
  
  W
  Wilson's Theorem   Theorem
  
  c
  coin problem  Section
  combinatorics  Paragraph
  
  ...

**Comment by mitchkeller** [comment]
I've just started throwing some `index` tags into my book as I've done some preliminary cleanup of the `sl2x` conversion and find the case sensitivity of the HTML index really annoying. Consider this a vote in hopes of getting the case-sensitivity bug resolved. I'm not thrilled with the idea of having to make every entry upper case to have the index make sense.

**Comment by davidfarmer** [comment]
In case I have not said this enough times already,
all index entries should be lower case, except those
that should be upper case, like "Riemann, Bernhard".

Those people who mistakenly think it is good to have
everything in the index upper-cased, can have it that way by
invoking a flag that upper cases the index entries as the
index is assembled.

If that flag does not exist yet, or if the index does not
yet alphabetize correctly with mixed case, then those are
feature requests/bugs which will be addressed.  People should
make proper index entries and assume things will work
properly when needed.

**Comment by rbeezer** [comment]
On 06/21/2016 02:12 PM, davidfarmer wrote:
> If that flag does not exist yet, or if the index does not
> yet alphabetize correctly with mixed case, then those are
> feature requests/bugs which will be addressed. People should
> make proper index entries and assume things will work
> properly when needed.

Right. Just getting any kind of index working in HTML (ie what you see now) was 
a major project.  Most of my discretionary time for a whole month during the 
semester.  It has long rough edges.

The LaTeX index generation has years of fine-tuning in it.  Indices are a real 
minefield, much like last names.  We'll slowly make progress on getting basics 
(like mixed-case) right and work our way down the list as we can.

But your source should be safe.  Except I want to deprecate "index" so I can use 
it where I now have "index-part".  Then index entries will be "idx".  I will 
write an automatic converter to translate, or you can do it with sed.  So do not 
hold up on an index for this reason - if you say you will come back to it, then 
you never will. ;-)

Fix up index.  Well, OK, after I deprecate "index".  But write a tool to fix 
those first.  Things get stacked up that way....

@Mitch - you could help this happen sooner by making an omnibus issue, "Fix 
index"  Then make an issue for mixed-case and cite the omnibus issue in it. 
Then find KDC's recent "seealso" request and cite the omnibus issue there also. 
  This way I can see on the omnibus what can be done simultaneously and 
everybody can track/prioritize various aspects.  Thanks.

Rob

**Comment by kcrisman** [comment]
@davidfarmer I don't think that it's fair to assume that anyone is necessarily randomly making index entries uppercase for fun.  I currently have dozens of uppercase ones in my project, and only "Python", "Sage", and "FTA" are not proper names (e.g. "Korselt's Theorem", "Riemann Hypothesis", unsure if second word should be cap there but it's traditional).  I (and presumably @mitchkeller ) just want to vote for this eventually working, which I am confident @rbeezer will accomplish 😃

**Comment by davidfarmer** [comment]
I guess I was not clear: I was saying that it is wrong to
make every index entry upper case.  You do not seem to be disagreeing
with that.

**Comment by kcrisman** [comment]
>
> I guess I was not clear: I was saying that it is wrong to
> make every index entry upper case. You do not seem to be disagreeing
> with that.
>
>
No, but what I am saying is that perhaps Mitch wasn't saying that either.
He was just trying to figure out how to get all the index entries together,
and since lowercase isn't an option for "Riemann, B." that was his voiced
workaround suggestion since nothing else was (currently) working.

**Comment by mitchkeller** [comment]
On Jun 22, 2016, at 8:08 AM, kcrisman <notifications@github.com<mailto:notifications@github.com>> wrote:

>
> I guess I was not clear: I was saying that it is wrong to
> make every index entry upper case. You do not seem to be disagreeing
> with that.
>
>
No, but what I am saying is that perhaps Mitch wasn't saying that either.
He was just trying to figure out how to get all the index entries together,
and since lowercase isn't an option for "Riemann, B." that was his voiced
workaround suggestion since nothing else was (currently) working.

That’s the correct interpretation of things. I recognize that capitalizing everything is poor indexing, but it seems to be the only thing that would work for both LaTeX and HTML at the moment. I’m glad to have it confirmed that this is considered a bug, but I wasn’t sure after looking at AATA, since the index there has every term capitalized from what I could see.

The really weird thing I’m noticing in looking at mathbook-html.xsl is that it appears steps are being taken to destroy the case sensitivity, but it seems like they’re just not working as intended.

--

Mitch Keller
Assistant Professor of Mathematics
Washington & Lee University, Lexington VA
206 Robinson Hall ~ 540.458.8099 ~ http://www.rellek.net

**Comment by rbeezer** [comment]
Just looked at AATA source, and indeed it seems every index term is capitalized.  That was my primary test vehicle as I debugged this (and perhaps had not realized the situation), so that may explain why the code is not always doing the right thing.

@twjudson you might find David's style advice above useful.

@mitchkeller keep authoring your source properly and the code will catch up.  Tom could tell you tales.

**Comment by kcrisman** [comment]
> Just looked at AATA source, and indeed it seems every index term is capitalized.

I just looked at the sample article, and there is only one index item which is _not_ capitalized 😉

**Comment by rbeezer** [comment]
Case sensitivity is resolved at #409.

No plan to put numbers on references that are knowls.  Type indications are already better than page numbers, and will retain some sense of mystery about what is behind the doors.
