### ISSUE TITLE
Can't click on contents or "book icon" links

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#29]
In the default presentation, there is a little book symbol on the upper left which does nothing useful (keeps you on the same page but reloads) and the word "Contents" does not give you the front TOC page as one might expect.  In effect, it becomes impossible to go up to the top without clicking "up" several times when drilled far down into a `<book>`.

**Comment by rbeezer** [comment]
Click on a chapter heading and then click up arrow.  Two clicks.

"Contents" was once clickable to hide it (I think).  It was never meant to be clickable as navigation.  So the one thing to do here is to turn off its clickability.

The little book is no good until you enable it.  From Judson's algebra

```
<docinfo>

    <brandlogo url="http://abstract.pugetsound.edu" source="images/cover_aata_2014.png" />
```

You could make it link to whatever you like.

**Comment by kcrisman** [comment]
> "Contents" was once clickable to hide it (I think). It was never meant to be clickable as navigation. So the one thing to do here is to turn off its click ability.

I would argue that should be configurable, but I take your meaning.

> Click on a chapter heading and then click up arrow. Two clicks.

There should always be a way to "go home" in one click on any larger site - preferably with a link that looks like a house?

**Comment by kcrisman** [comment]
I thought about this some more (while working on more conversion) and I think this ticket should be for the following two things.
* Make "Contents" actually work to hide the contents (a very typical thing), or turn it off and then open a new ticket for that.
* Make the title of the book itself clickable, e.g. at http://linear.ups.edu/html/fcla.html you have "A First Course in Linear Algebra" twice, once little and clickable, once not; the title itself should bring one to the title page/toc (default setting, anyway).

**Comment by davidfarmer** [comment]
If you are on a smartphone then the navigation changes and the
three horizontal bars show or hide the TOC, as usual.

We tried and failed to come up with use cases and suitable
defaults for showing and hiding the TOC when one is in a wide
browser.  We can reopen the issue if you wish.  Here is how I see it:

If you want to see only the text, in a browser that is only the
width of the text, then make the browser that wide and you have what
you want.

If you want to hide the TOC, so that the text is on the left of the
browser and there is white space to the right, then that would be
supported by an option to hide the TOC.  But what would be the
point of that, since you just replaced the TOC on the left by white
space on the right?

It would help if you could describe a situation where you want
to hide the TOC.

**Comment by kcrisman** [comment]
>
> We tried and failed to come up with use cases and suitable
> defaults for showing and hiding the TOC when one is in a wide
> browser. We can reopen the issue if you wish. Here is how I see it:
>

Umm, two obvious possibilities:
* When you want the browser to *not* take the whole width, but it's in that
awkward spot where the TOC still shows up.  I found it pretty easy to make
that happen just now in testing.
* When you just feel like you want more width, say for really long
equations or paragraphs one doesn't want squished.

By the way, there is a lot of wasted space on the right of the browser when
it's super-wide.  Makes sense for the typed output, not so much for browser.



> If you want to hide the TOC, so that the text is on the left of the
> browser and there is white space to the right, then that would be
> supported by an option to hide the TOC. But what would be the
> point of that, since you just replaced the TOC on the left by white
> space on the right?
>

Why not just have it expand on the right?

**Comment by davidfarmer** [comment]
We decided that there should be a fixed maximum line width, except for
equations which can run wide into the right margin.  (Which is at least
partially caused by the fact that you need a bigger font in equations
to make them readable on a computer, so equations which fit the text width
on the printed page may appear wider in a browser.)  If you make the
browser very wide, then yes, there is a huge amount of space to the
right of the text.

That maximum line width is approximately the width that would appear
in a well-typeset printed book.  A few hundred years of book design
seemed like too much thoughtful work to throw away.  If someone wants to
make their browser really wide and read lines with 300 characters
in them, then they will have to figure out how to over-ride the
current CSS.  I certainly would not support that feature in the main
distribution.

As to making the option of hiding the TOC:  of course it is possible
to adjust the browser width so that it appears desirable to hide it.
But essentially the same effort can just make the browser a bit narrower
and then it is hidden by default.  That is an argument that there is
no pressing need for that option.  But I suspect the argument that
trumps everything is that it is surprisingly nontrivial to write the
javascript that hides the TOC and also shifts everything else to
the left.  We tried that and failed, although that could be because
of a lack of skill, or more likely the design of the html markup
makes it hard to have that feature.

**Comment by kcrisman** [comment]
> We decided that there should be a fixed maximum line width, except for equations which can run wide into the right margin.

I'll point out that code also does this.

> A few hundred years of book design seemed like too much thoughtful work to throw away.

Ordinarily I would agree... though let's note that the width of modern highway lanes is at least partly related to the width of Roman axles, or so urban legend would have it.  I think there is enough evidence out there that reading on computers is different (possibly worse) than print.  Actually, I find it just as annoying that when I increase the font size in my browser sometimes the menu on the left goes away.

> But essentially the same effort can just make the browser a bit narrower and then it is hidden by default.

Yes, but the user may not know this, or the browser may already be that width for some other reason (e.g. last window was at this level) or whatever.

I'm really not thinking of my own use at all.  I'm already crazy enough to be using this tool in the first place!  But my students are not, and are not projecting on a huge screen, and so will find that extra space on the right ... curious, at least.

> But I suspect the argument that trumps everything is that it is surprisingly nontrivial to write the javascript that hides the TOC and also shifts everything else to the left. 

That would definitely trump things.  It surprises me, though, having used so many sites with precisely this option (no, don't ask me to remember which ones!).

Anyway, it's clear that I am not going to prevail here, so at the VERY least I suggest humbly to do this request:

> Make the title of the book itself clickable

I hope there is nothing particularly controversial about that, and it would solve one of the problems (needing two clicks to the front page) which I do consider a problem, albeit more minor than some of the authoring things that are still WIP.

And of course disable the click ability of the Contents, if one really can't use it as a toggle.

**Comment by rbeezer** [comment]
At 0363abb0 the title becomes a link to the very top level (document root).  Thanks for the (early) suggestion.

The only think left on this ticket is the `Contents` button above the scrollable table of contents, which I have moved off to #424
