### ISSUE TITLE
allow line in dedication and similar places

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#308]
See https://groups.google.com/forum/#!topic/mathbook-xml-support/dwV2o89cJPA

> Yes, dedication, credit and similar things need some work.
> It should work just like this, I think I made "line" work in dedication, though maybe it is not in the DTD.

**Comment by kcrisman** [comment]
One of my few remaining DTD violations...

**Comment by rbeezer** [comment]
In a `dedication` you can have multiple `p`, since you may have multiple authors, or multiple people to dedicate to.  Then each `p` can be structured by `line` if you want to control the line breaks.

Work from May 2016 at f92234371f375f2027af743e4767b83c3ab5249e

If the `p` are too close together, create a new issue for that, please.

**Comment by kcrisman** [comment]
Thanks.  In the meantime this no longer violates in any case.  Thanks!
