### ISSUE TITLE
Appendices do not appear in proper place in LaTeX

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#31]
If I put an `<appendix>` element inside a `<chapter>` or `<section>`, it looks great in HTML.   However, in latex it becomes its own chapter.  Not good for maintaining the same numbering scheme!

**Comment by kcrisman** [comment]
Yes, the tex has
`\chapter` but the place might be `\section` or even, in my case, `\subsection` that is needed.  Appendices should inherit from the higher-level element.

**Comment by kcrisman** [comment]
I'll point out, for what it's worth, that the `\typeout` business gave
```

************************************************
Appendix 3.7.1 When perfect squares divide each other
************************************************
```
as in the html, so in some sense this is a bug and not just user error :smiley:

**Comment by rbeezer** [comment]
Appendices are peers/siblings of chapters in books.  They are not meant to be subsidiary to chapters nor sections.  The "\typeout business" is not very sophisticated.

Perhaps an arricle could have appendices, as peers of sections, but they still would not be contained in a chapter.

**Comment by kcrisman** [comment]
Then this should be DOCUMENTED somewhere.  So please re-open and change the title.

Also, it should ideally raise an error then.

So... I definitely have read books with appendices to chapters.  Lots of times.  How can I do this in this magical "write once" MBX?  Seems a bit constricting.

**Comment by kcrisman** [comment]
(Especially since I'm not allowed to change the name of a subsection, for instance.)

**Comment by davidfarmer** [comment]
In some LaTeX styles, the \appendix command indicates that the
following chapters are appendices.   Those chapters are numbered
differently, but otherwise are just chapters.

So, in that case appendices cannot sit inside a chapter.

The same goes for a paper instead of a book, except replace "chapter"
by "section".

I'd like to know if/why we are departing from the LaTeX model.

**Comment by rbeezer** [comment]
Dear Karl,

I closed this because it is not a bug, but a design decision.

No need to shout about documentation, there really isn't any yet.  With time 
(and support) that will improve.  If you would like to start a *single* issue 
where you can add documentation suggestions that have bit you, I will work 
through adding them to the sample article for now.  That would be very helpful - 
I want the initial experience to be less bumpy.

Eventually the DTD will be finished and a validation step will alert you to many 
of these.  This will be the way an "error" is raised, it will not be recognized 
as such in each converter.  The DTD will be a formal specification of the XML 
structure and it will be an easy command-line step to validate.

Could you suggest a book with appendices in chapters (or appendices within 
sections) that I could look at?  Something I could likely get by interlibrary 
loan would be easiest.

Thanks,
Rob

**Comment by rbeezer** [comment]
On 22/01/2015 00:14, davidfarmer wrote:
> I'd like to know if/why we are departing from the LaTeX model.

I plan to keep appendices as peers of chapters in books.

I am open to appendices as peers of sections in articles, but have not 
double-checked if that is a natural construct in LaTeX.  An issue for this 
situation as a feature request might be in order, since I do not think it is 
implemented (but could be!).

Rob

**Comment by davidfarmer** [comment]
I have processed many math papers where

\appendix

shows up on a line by itself, and then the sections after that
are appendices.  I have also seen \begin{appendix}...\end{appendix}.
(One of my papers uses the first construction:  a coauthor set it up
that way.)

I have not decided how to handle appendices, nor have I started
implementing < part >s.

Let me know when you are ready to tackle one or both of those, and we can
do it together.  I can provide actual papers with examples.

**Comment by rbeezer** [comment]
And I belive that in one style or another, you say

\backmatter

and then every subsequent \chapter is realized as an appendix.

Yes, we should definitely coordinate on these.

Rob

**Comment by kcrisman** [comment]
> If you would like to start a *single* issue where you can add documentation suggestions that have bit you, I will work through adding them to the sample article for now.

That is a good idea.

I'll comment on the rest of what I was going to say on the list instead.
