### ISSUE TITLE
About the `tgroup` tag

### ISSUE THREAD

**Issue by cmhughes** [rbeezer/mathbook#34]
Hi Rob,
I've been wondering about the `tgroup` tag.

Referencing `sample-article.xml`, I see that you have code such as

```
 <table xml:id="table-euler1">
                <tgroup cols="4" align="center">
```

This puts all `4` columns as centered.

I've been working on a feature that allows the following mark-up:
```
 <table>
                  <caption/>
                  <coltypes>
                    <col align="center"/>
                    <col align="left"/>
                    <col align="right"/>
                    <col align="decimal" format="4.4"/>
                    <col align="decimal" format="6.6"/>
                  </coltypes>
```
which produces tables such as the following

![27644100-969d-11e4-8756-59b8876ed364](https://cloud.githubusercontent.com/assets/2224480/5888657/319c9e9a-a400-11e4-9d3a-4db18ffccac9.png)

Note that each column has different alignment, and that it also allows decimal alignment.

I have *another* feature (called `multobjects`) that allows multiple tables, multiple figures, figures and tables, subfigures, subtables, to be placed next to each other.

Both of the features that I have developed do not use the `tgoup` element. Before I submit these features for your review, I wondered if I could know your thoughts on the `tgroup` tag--other than column types, what does it do? :) If I've misunderstood its use, I'm sure I can work it back into my features.

Thanks for your time
Chris

**Comment by kcrisman** [comment]
Just let me put in a vote to allow as much customization in tables as possible... but also in HTML, where it might be harder?

**Comment by rbeezer** [comment]
Dear Chris,

I'm not sure what `tgroup` does either.

I began by trying to implement the "XML Exchange Table Model" which is a subset of the (failed) CALS table model.  So that is where `tgroup` comes from.  But I'm not happy with it, as I think I misuderstood some aspects of its approach when I first researched it.

I have a very good idea of how I want to implement almost every missing feature of MBX *except* for tables.  HTML and LaTeX have very different capabilities, and it strikes me that you can do more in LaTeX (maybe).  At the moment, I'm leaning to starting from scratch and starting simple.  But whatever gets specified, it needs to be realizable in both LaTeX and HTML.

So no matter what, I suspect tables will require some editing down the road.  Tom Judson is just doing them in raw LaTeX and letting MathJax render them on the HTML side.  So adding too much to what exists now might be premature.

I like the alignment - is that image from an HTML rendering?  If so, it should be easy to duplicate on the LaTeX side (maybe you have, I'm not caught up enough just yet to check the code).

Anyway, let me know your thoughts on going slow on this one, or trying to coordinate some of what you are doing with some of my own (ill-formed) ideas.  Perhaps a discussion on the support list about possible approaches is in order?

I'm back home, courses are partially under control, and I'm hoping to use much of Wednesday to get to some of the outstanding MBX discussion and code.  And I hope to be more responsive in the days ahead.

Thanks for your contributions and interest.

Rob

**Comment by cmhughes** [comment]
Hi Rob,
Thanks very much for the follow-up, and for you consideration of this idea.

I have duplicated the alignment I showed previously in LaTeX using siunitx
decimal alignment; as you say, it's straightforward.

I think that the xml structure that you have for tables is solid; the only
tag that I haven't understood is the tgroup (hence this thread!)--I can see
value in thead, tbody, row, entry, and caption.

As far as development goes, I'd be interested in bundling up my progress
into a pull request so that we can review it together. It might not be the
perfect solution initially, but perhaps we can all work on it to get a
solution that is robust enough for us all to use--how does that sound?

Thanks again for your time.
Best
Chris

**Comment by kcrisman** [comment]
I think this tag has now been removed, see examples/sample-errors-and-warnings.xml

**Comment by kcrisman** [comment]
(That is to say I'm not sure what this issue is currently about, so it might be helpful to change the title or open a new one.)

**Comment by Alex-Jordan** [comment]
I'm combing through old issues. Is this one that can now be closed? `tgroup` is no more, and `multobjects` became `sidebyside` (I think).

**Comment by rbeezer** [comment]
We can close this one.  I'd been keeping it open while decimal alignment was outstanding, but that can be pursued somewhere else.  Thanks for the prods.
