### ISSUE TITLE
sidebyside and \textwidth

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#432]
Consider whether to use `\linewidth` instead of `\textwidth` for width specifications on print sidebysides. Use case: a `sidebyside` inside an `exercise` that is part of an `exercisegroup` (which is technically presently DTD supported, since `statement/sidebyside` is supported).

CLM  has these, for example at http://spot.pcc.edu/math/clm/functions-derivatives-antiderivatives-supplementary-exercises.html. [At the time of posting, this links to old HTML that will be replaced by January. The sbs graphs look bad at present, but the point is there is a sbs within an exercise that is within an exercisegroup.]

**Comment by Alex-Jordan** [comment]
Found it. This issue should be tagged with `sidebyside`.

**Comment by Alex-Jordan** [comment]
Not entirely sure about everything I meant in the OP, but if a sbs is used in an indented environment, then having the architecture based on `textwidth` can make the sbs content spill out into the margin. Because in an indented environment, `textwidth` is larger than `linewidth`, and includes the indentation.

**Comment by rbeezer** [comment]
Thanks.  I made it a "bug" also, so it rises a bit higher in my reviews of things to do.  I understand the problem, just want to be certain I get all the cases.

**Comment by rbeezer** [comment]
Reporting and recording.

A LaTeX `sidebyside` is a collection of minipages inside a tabular inside a figure.  That makes everything pretty and centered.

Put a `sidebyside` deep into a nested list and you need to unwrap the `figure` and maybe get rid of a pesky `\leavevmode` (and replace by a `\\`  in order to have it render like you would expect.  

But then with the textwidth/linewidth change suggested here, it indeed scales properly, and so on.

So perhaps the sidebyside should just be a `tabular` with manual line-breaking before and after?

**Comment by rbeezer** [comment]
Actual change is at 6567a211, but also some other work nearby, like unwapping some LaTeX figures which are not necessary anymore (as suggested above).

There are still some `\textwidth` about, which I will edit eventually, but all of the `sidebyside` ones are gone.  Testing with a 4-level indented list went perfectly.
