### ISSUE TITLE
MathJax zoom on displayed math

### ISSUE THREAD

**Issue by cmhughes** [rbeezer/mathbook#5]
Hi Rob,
This is a great project! We met last year (June 2013) in Vancouver at the WeBWorK coding camp.

I've been playing with the mathbook, and it works very nicely. I have noticed that when viewing the html version, if I enable Zoom factor for MathJax, then the displayed math mode gets cut off when zoomed in. I'm using the `sample-article.xml`; I've posted a screenshot here:

http://spot.pcc.edu/~chughes/nozoom.png

It seems like the issue stems from:

http://aimath.org/mathbook/mathbook-modern-3.css

Do you have any insight on this?

Chris

**Comment by Alex-Jordan** [comment]
It's been a while since this thread had discussion. Here is the behavior I see now. I'm wondering if this is still an issue or if this can be closed. Chris's original example is gone now, so I can't compare exactly to what I see.

I am looking at a large multiline equation that almost fills the central panel.

If my screen is very wide, there is no need for scrolling. If I trigger the MathJax zoom, then it zooms fully and there is no cropping or need for scrolling.

If I narrow my screen some, to the point where the un-zoomed content is still fully visible, but now the zoom box doesn't fit, then in the zoom box, I get a horizontal scroll bar. The zoom box is still tall enough for all of the rows.

If I narrow my screen to the point where the un-zoomed content requires a horizontal scrollbar, then the zoom box is shorter than its content and has both horizontal and vertical scrolling. The vertically cutoff and scrolling seems unnecessary. Is this the only thing that is less than ideal at this point?

**Comment by rbeezer** [comment]
Does seem to have improved greatly.  But try this:

Single-line displayed equation inside a knowl.  Zoom factor 200%.  Browser width 
just wide enough to contain ToC sidebar and all of the knowl.

Double-click to zoom and just get the top edge of the zoom box visible in the 
region containing the equation.  Can't see any math in the zoom-box.  Widen the 
browser window in discrete baby steps and quickly (not immediately) the box 
becomes visible (same location) with a horizontal scrollbar.

**Comment by Alex-Jordan** [comment]
I see the same issue. Firebug tells me the zoom box I'm looking is:
`<span id="MathJax_Zoom" style="font-size: 200%; max-width: 363px; max-height: 4px; left: -432px; top: -17px;">`

And if I directly change that `max-height: 4px;` to something larger, or even better just delete it, then I see full height. Likewise I can increase `max-width` to get something more reasonable.

But the point is, MathJax is in control here. These are inline CSS attributes within the actual zoom box. MBX's CSS can't overrule them. Maybe MathJax can be configured to help though.

**Comment by rbeezer** [comment]
Do you read the [mathjax-users] group?

I have a good live example (in AATA) though not minimal.  I don't mind posting 
to ask, but would perhaps need help with the technical discussion that would ensue.

It seems like we are close to having this work well, and they might be 
interested in the scenario?

Rob

**Comment by Alex-Jordan** [comment]
I don't receive updates, but it's in my list of "recently viewed". I could add it to my rounds of checking mathbook and ww-mbx. (I don't get updates on these either. For whatever reason I prefer to just drop in and catch up.)

Might be good to (at least try to) rule out a MathJax config solution first. I'll post here if I do that.

**Comment by davidfarmer** [comment]
I read that newsgroup.  It will be much appreciated if your posting, when
you are ready to do it, contains a link to a live example.

The discussions on MathJax/javascript/etc are usually over my head,
but Davide Cervone is great and is likely to post a useful reply.

**Comment by Alex-Jordan** [comment]
I posted a question: https://groups.google.com/forum/#!topic/mathjax-users/lDSG0OQWPzk

**Comment by rbeezer** [comment]
I just saw it, and will watch.

**Comment by Alex-Jordan** [comment]
David F just did some CSS edits that appear to address this. We checked in Firefox, Chrome, Safari.

**Comment by rbeezer** [comment]
Thanks!
