### ISSUE TITLE
CSS surrounding WeBWorK conclusion

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#503]
If you go to:
http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-1.html
and click to open the first WeBWorK knowl, it opens after the conclusion instead of before the conclusion. 

In trying to address this, we should be careful not to break something else. I'm shortly going to submit a PR with a new section in the WeBWorK sample chapter that demonstrates every combination of components that would go into a WeBWorK layout. Best to get that up before trying to work on this.

**Comment by rbeezer** [comment]
The knowl there, whose clickable is `WeBWorK Exercise` **is** wrapped in a `div.hidden-knowl-wrapper`  The **only** purpose of that `div` is to give the knowl something to open up right after.

So it is a bit of a mystery to me why the knowl finds its way below the conclusion to open.  I think @davidfarmer might want to take a look?

**Comment by rbeezer** [comment]
#504 has now introduced lots of situations for testing.

**Comment by Alex-Jordan** [comment]
See: http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-11.html for all 2^4 combinations that I am aware of.

**Comment by Alex-Jordan** [comment]
I've noted this elsewhere, but I think I should repeat it here.

I think it looks good for the WeBWorK knowl to be inline with the exercise number when there is no introduction. Regardless of whether there is a title. Regardless of whether the exercise is free range or sectional.

If there is an introduction, I think it is best to have the introduction inline with the problem number, and have the WeBWorK knowl reset to start a new block. Regardless of whether there is a title. Regardless of whether the exercise is free range or sectional.

All of this is currently in place. However I think that part of what is making these things work out is responsible for the knowl opening subsequent to conclusion elements. (Because the WeBWorK knowl's surrounding div has display:inline.)

**Comment by Alex-Jordan** [comment]
@davidfarmer Would you take a look at this when have a chance? In summary, if you go here:
http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-11.html

Then you can see how exercises 11.1.5--11.1.8 open up _after_ the conclusion.

**Comment by rbeezer** [comment]
High probability this ball is in my court, likely due to lacking a div.

The request to make knowls more configurable for WW exercises was almost 
unattainable, since they were grafted in under certain assumptions that are now 
being requested to change.

These things ("environments") need a (another) major refactor.

**Comment by davidfarmer** [comment]
The problem is that the hidden-knowl-wrapper around the
"WeBWorK Exercise" knowl is set to be display: inline.
So when the knowl looks for the nearest enclosing block element,
it goes to the next level out.

In other contexts, the hidden-knowl-wrapper is block level,
which it needs to be because its whole purpose is to make
the knowl open in the right place.

So, there is a tension between standard knowl behavior and
having "WeBWorK Exercise" appear inline.

Let's think for a while before making any changes, because right
now it looks like both the HTML markup and the CSS have to change,
and it is best to not be too hasty with multiple changes.

**Comment by davidfarmer** [comment]
This is fixed. 

I modified the knowls code so that if the parent() (or parent().parent())
hasClass("hidden-knowl-wrapper"), then the knowl opens after it.

Please confirm and then close.

**Comment by Alex-Jordan** [comment]
Why is it different here (http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-11.html, 11.1 exercise 1) compared to here (http://greenprecalc.com/precalc1-MHCC/composition-and-inverse-gist.html, 7.3.3 exercises)?

I just processed and posted the latter example's HTML this morning, and my mathbook repo is up to date.

**Comment by davidfarmer** [comment]
The 7.3.3 exercises have an article.introduction which contains
only an empty paragraph.  That causes the exercises to be pushed
to the next line, so it is an unrelated issue.  (The current
issue is about where the knowl opens, not where the knowl link appears.)

If that empty p was eliminated (and the empty article), then the
display should be fine.

**Comment by Alex-Jordan** [comment]
This was almost certainly fixed by David long ago. But it's also moot now, because we will no longer be knowlifying a webwork alone. (Now you just knowlify the entire exercise if you want.)
