### ISSUE TITLE
No number in display math, when requested

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#528]
`md` creates display math without numbers.

`mrow/@number='yes'` should elect a number for that row only, but that is not happening for LaTeX output.  Need to review HTML also.

Two strategies:
  * use a numbered `align` environment and `\nonumber` all the other equations.
  * use the unnumbered environment `align*` and "manually" step the equation counter before using `\tag{}`

Not sure which is less ugly, the latter could use a macro, but then the math bit is less portable.

http://tex.stackexchange.com/questions/42726/align-but-show-one-equation-number-at-the-end

**Comment by davidfarmer** [comment]
I presume the only issue is how MBX translates to LaTeX.

In terms of giving people LaTeX that looks like what people
author, nonumbering all the other rows of that display is
the more common thing that actually occurs more in the wild.

I think that is also the "right" thing to do, because it involves
higher level operations.  Users should not be thinking in terms
of manipulating internal counters.  And it is undesirable to
create a new "numberthis" macro.  (Unless we want to consider
numberthis to be one of our "standard" macros.)

**Comment by rbeezer** [comment]
On 02/13/2017 03:15 AM, davidfarmer wrote:
> nonumbering all the other rows of that display is
> the more common thing that actually occurs more in the wild.

Thanks, it helps to know what a human is most likely to do.

No, I was not too wild about stepping a counter, macro or not.  But also seems 
silly to "nonumber" all but one equation to get a number, but I guess that is 
where we are.  No problem for an author in MBX, anyway.

**Comment by rbeezer** [comment]
Fixed at 6fd5fbb9

This fix is minimally invasive, and for LaTeX only.  See #529 for follow-on.
