### ISSUE TITLE
comment element

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#544]
This is a feature request.

I would find it useful to have a `comment` element. Sometimes there is a large block of source I would like to comment out, like a subsection. Within that subsection, there may be lots of XML comments using `<!--  -->`. When this happens, I can't comment out the whole subsection easily because XML does not permit nested comments. If I could wrap the subsection in `<comment> </comment>`, and the template for a `comment` just killed everything inside, that would make this task easy.

I think the XSL for such a thing would be fairly simple: just put and empty template inside common. (Perhaps the knowl factory would need to explicitly be told not to look inside a `comment`.)

My motivation is as described above, but consider these extra features that would come along for the ride. Numbering would stay intact (assuming I understand how numbering works). So if you `comment` out section 2.3, then the output will show 2.1, 2.2, 2.4, ... unlike what happens with`<!--  -->`. Cross-references pointing to commented out content would still be written without errors (but of course their targets would not exist).

**Comment by rbeezer** [comment]
Let's discuss this one on the main list.  If you start, I'll reply sometime today.

**Comment by rbeezer** [comment]
This is more about debugging, not about the nature of source code.  And I've been fooled more than once by (numbered) items left in source XML inside comments, where output and grep'ed counts do not match.

I agree that lack of nested comments is annoying.  I've just cut out huge sections in an extra file, and then pasted them back later.

So I do not see a "custom" XML element in PreTeXt as the solution to this problem, and potentially the source of more trouble, rather than less.
