### ISSUE TITLE
Calculator (such as Desmos)

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#589]
Put a "calculator" button in the top bar (between Index and Prev) which
opens Desmos on the page.  Maybe in the right margin if wide enough,
or knowl-like in the page?

**Comment by rbeezer** [comment]
It is relatively trivial to embed Desmos into a page.  Great example page from Ann Cary:

http://spot.pcc.edu/~acary/desmos.html

So, easy to put in a knowl.  But I'd love to see it pop in/out of the right margin, and then use as much real-estate as possible.  Maybe even grow/shrink as enclosing window is changed.  (Maybe the "iframe resizer" Alex uses for WW problems would be useful?)

Who goes first?  We add a calculator button, controlled by a switch?  Not all disciplines will want one.  iframe goes into some div that CSS/JS moves into margin?

I guess I need guidance on what my role is in this, since I don't know how to manage the right margin.  In other words, who goes firat?  No rush, but I think this will be a really nice feature.

**Comment by davidfarmer** [comment]
First let me add the enhancement to knowls which will
let the link be in the margin (or the top bar)
and the content appear in the page.  Once the basic
functionality is there, then we can try things and see
what works best.

**Comment by davidfarmer** [comment]
We have a calculator now.
