### ISSUE TITLE
WW exercises should be in hidded-knowl-wrapper s

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#615]
The WW exercises on this page:

http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-11.html

are in bare div's.  Those div's should have class="hidden-knowl-wrapper"

**Comment by rbeezer** [comment]
Right. Good catch.  A WW problem in an embedded knowl (which is what these are in the general structure of producing knowlized content) would not render.

So I had put in a hack to realize these as external-file knowls.  That results in the bare divs, absence of "hidden-knowl-wrapper", etc.  I should know better than to cut corners.

So I unwound the hack and I think all the CSS is now working right.  But the knowl does not.

@Alex-Jordan will need to know.

**Comment by rbeezer** [comment]
It is possible I could move the hack more interior.  In other words, not so many changes to the surroundings, just change the `a` tag.

Does the styling depend on any aspects of the `a` tag which is the actual knowl link?

**Comment by rbeezer** [comment]
Forgot to include the relevant commit.   cf0f943c

**Comment by rbeezer** [comment]
I restored the hack, but only changed the anchor tag, so the WW exercise is being served from an external file, not an embedded knowl.

@Alex-Jordan   please check that you like the formatting now.

I'm closing this, since the styling problems are solved, and moving it to a more general issue.

See https://github.com/rbeezer/mathbook/issues/629

**Comment by Alex-Jordan** [comment]
The layout issue is addressed. I'll alert Matt to rebuild HTML for Active Calculus.

**Comment by rbeezer** [comment]
Thanks for checking.
