### ISSUE TITLE
CSS for titles of unnumbered sections

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#62]
For example, in a `preface` element, with a title, the title comes out with space before it. I think the space is meant to be there between a section number and the title, but since there is no number, the title looks oddly indented.

**Comment by rbeezer** [comment]
Thanks.  Titles are harder than they look, and I know they are a bit of a mess 
right now as far as manipulating them with CSS, and the like, to get various 
parts to show/hide.

I get some hard carriage returns in my HTML output that I swear are a bug in 
xsltproc, so that leads to some unwanted spaces also.  This marker will help me 
remember to put some work into these.

**Comment by Alex-Jordan** [comment]
Seems like this is working now based on http://mathbook.pugetsound.edu/examples/sample-book/structural/html/preface.html and surrounding unnumbered divisions.
