### ISSUE TITLE
Unify numbering depth between chapters and appendices

### ISSUE THREAD

**Issue by oscarlevin** [rbeezer/mathbook#689]
Currently, in a book, a subsection of a chapter is depth 3, but in an appendix it is depth 4.  This makes it hard to specify at what depth numbering should be turned off if appendices are used as "supplemental" chapters.

**Comment by rbeezer** [comment]
I believe this is fixed at  2c4f330b, due to testing on three comprehensive examples.  However, @oscarlevin , a test on your project would be really appreciated.

I may add on some related code-cleanup work, hopefully with zero changes in output, so you can checkout this particular commit if there is more possible testing.  That work will be on #551

Thanks very much for the report.  Turns out I was on to this one back on #551, but had left it behind.

**Comment by oscarlevin** [comment]
This seems to be working now.  Tested the bogart book at maximum level 2, 3, and nothing at all, and everything worked as expected in both html and latex.

**Comment by rbeezer** [comment]
Thanks very much for the testing.

A few more zero-impact changes coming, which may in truth fix some bugs I did 
not even know about.  ;-)
