### ISSUE TITLE
Index for Sample Article does not exist

### ISSUE THREAD

**Issue by nwintersgill** [rbeezer/mathbook#726]
The link to the index for the Sample Article does not work - it leads to a file that does not exist.

I pulled to update PTX, built the sample article, and the index did not get created.

**Comment by Alex-Jordan** [comment]
It seems that in article, an index is just one of several appendices all on the same backmatter page.

**Comment by rbeezer** [comment]
Thanks for the report.  I'm not sure which link you mean.  Could you describe 
just where it is?  And perhaps what the name of the non-existent file is?

Thanks,
Rob

**Comment by rbeezer** [comment]
At the *very bottom* of

http://mathbook.pugetsound.edu/examples/sample-article/html/backmatter.html

**Comment by nwintersgill** [comment]
Thanks. I've found the index in the backmatter, but I was originally referring to the index button next to contents at the top. Whenever I click on it, it gives me a "file not found" error.

**Comment by Alex-Jordan** [comment]
The index tab button in the top nav bar takes you to http://mathbook.pugetsound.edu/examples/sample-article/html/index-1.html which doesn't exist.

Same if you click the Index nav button in the References section in the left nav panel. But not if you have already gone to the References section, in which case pushing the button does take you to the right heading within that section.

**Comment by rbeezer** [comment]
Got it!  Thanks.

I think we've only ever tested that in books.  ;-) Fix should be easy.

**Comment by rbeezer** [comment]
Thanks, Nathan, for reporting this one.

Turns out link was not bad, entire structure of `backmatter` was off.  Divisions of backmatter are like `section` in an article, so previously inside of one huge webpage, when it should have been chunked into several pages (and link would then be correct).  Level counting is where the fix was needed.

Fault was introduced with 2c4f330bd2a19c5b0756ca718b01478b90326e2a (thanks, `git bisect`) and you can see I recognized something was wrong at 9f17bcf9dedf9985cd2f5eea4e1d28430630ff16 (thanks, `git blame`).  Fix is at 9856e5950db552085ffaea227906ba7313d4248e.
