### ISSUE TITLE
Empty p in sample article

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#742]
Empty p before first list in Sample Article section 12.1 ,
before the list in Definition 12.1, and before the
list in Section 12.7.  No other places on that page.

**Comment by davidfarmer** [comment]
Also before the list in the Answer(Helpful) knowl to exercise 3 in Section 16.

And before the display equation near the bottom of Section 18.

**Comment by rbeezer** [comment]
I have not looked, but am certain these are all due to a PTX "p" starting right away with a list or display math.  I understand the cause, and the difficulties it creates for designing CSS.  This is #777 again.

Here is the holdup:
*  Author puts an index entry into a "p" (which is natural and reasonable).
*  Resulting cross-reference in the index points back to that PTX paragraph.
*  But that logical PTX paragraph has been exploded into multiple HTML block elements.
*  The HTML id that is the target of that cross-reference presently goes on the first portion, an HTML "p", which may be empty if the author's "p" begins with a list or display math.

These opening empty paragraphs could go away if
*  A replacement is suggested to hold the HTML id/target
*  We agree that authors should never lead with a list, display math, or similar.  (Doubtful, despite our own convictions, since folks sometimes want lists all by themselves, so just wrap them in a "p".)
*  Right now display math is just bare text and not inside an element that is a sibling of the other parts of the exploded paragraph.  It might be useful to wrap it in a div, even if it does nothing.  Then an empty HTML paragraph could be removed, the id of the logical PTX paragraph could move to the next element.  I think this can be done technically, but I really do not like this approach.  Though wrapping the math in a div might be a good idea, independently.
*  The logical PTX paragraph is wrapped in a div, which could hold the id (and light up entire paragraph via pink flash).  This is the solution that makes the most sense to me.  Maybe the CSS refactoring suggests this is possible.  I suspect we would want to perhaps style the HTML "p" that are constituents of an exploded logical PTX paragraph differently than the entire logical paragraph.  Wouldn't we want more vertical space before/after the author's paragraphs than before/after lists, display math, and text all mixed up in a single logical paragraph?

**Comment by davidfarmer** [comment]
Here is an argument that such scenarios do not occur in practice.

We are assuming that it is reasonable to start a p-paragraph with
math or with a list.
And we are assuming that such a p-paragraph contains an idx entry.

The question is: where exactly is that idx entry, and what does
the 'in-context' link to?

If the idx is in an entry of the list, then everything is okay, right?
The in-context goes to the list element.  And if the idx is in the text
after the list but before the end of the p-paragraph, then the in-context
goes to that (non-empty) HTML p, and that is okay, too (assuming this
has been implemented)..

So, for the scenario of list in a p-paragraph, we only need to forbid
idx after the start of the p-paragraph but before the list (in the place
where there are no words).  I am okay forbidding that. [a discussion
about placement of idx markup might help: I think it should go immediately
after the term being referenced, or at the end of the paragraph.]

The case of display math in a p-paragraph is similar, except that
you can't put an idx inside the math.  Therefore the idx has to go
after the math, where there are actual words that will become an
HTML p.

The only work is to recognize an empty HTML p, remove it, and
make the next HTML p the target.

That is assuming you allow a PTX-p to start with display math
(if it were up to me, I might not forbid it, but I would not
promise reasonable behavior from such source).

>  *  We agree that authors should never lead with a list, display math, or similar. (Doubtful,
>     despite our own convictions, since folks sometimes want lists all by themselves, so just wrap
>     them in a "p".)

A list alone in a "p" is not a problem.  The possible problem is a p
starting with a list and then (for some reason) having text after that
list in the same p.

>     does nothing. Then an empty HTML paragraph could be removed, the id of the logical PTX
>     paragraph could move to the next element. I think this can be done technically, but I really
>     do not like this approach.

Not sure why you don't like it.

Re-reading what I wrote, it seems like the following resolves everything:

1.  If a PTX-p starts with a list, then the list is the only thing in that p.
     idx entries go in the list items.

2.  A PTX-p cannot start with display math.

>  *  The logical PTX paragraph is wrapped in a div, which could hold the id (and light up entire
>     paragraph via pink flash). This is the solution that makes the most sense to me. Maybe the
>     CSS refactoring suggests this is possible. I suspect we would want to perhaps style the HTML
>     "p" that are constituents of an exploded logical PTX paragraph differently than the entire
>     logical paragraph. Wouldn't we want more vertical space before/after the author's paragraphs
>     than before/after lists, display math, and text all mixed up in a single logical paragraph?

I understand that my suggestion throws away some of the structure in
the HTML version.

I am still having trouble weighting the merits of a div for the logical p.

Regards,

David

**Comment by rbeezer** [comment]
This sounds possible.  Here are the caveats:

1.  Identifiers are assigned by analyzing XML source, so when we bust up a PTX-p into an HTML-p and friends we have components that are not part of the XML source anymore.  I had not thought about the fact that ol/ul/dl cannot be pointed to (they are containers), and li can be pointed to (they have content).  So maybe we are OK.  Similarly, you can't point to `md` but can point to `mrow`.

2.  Display math goes into HTML bare.  I'd like to put it in a `div`, similar to how the other parts of a busted-up PTX-p are block-level items.  This might be a good first step, in isolation for a little while to gauge effects.

3. 
>The only work is to recognize an empty HTML p, remove it, and make the next HTML p the target.

Two out of three ain't bad.  Saving an id and "moving" it somewhere else is the kind of thing that is hard in XSL.  I'd prefer to make the next "thing" the target, no matter what it is (thus the `div` on math).  `cd`, and `men` are other possibilities for "thing", in addition to `li` and `div` from (2).

4.  Some of the source restrictions you suggest may be hard to code in the schema (likely because my skills aren't that good).  If none of the above bothers you, we might be able to remove your restrictions, since an `idx` in a `p` will just end up pointing to the first "thing" in the "p".

So re-reading, I'm proposing

(a) display math gets a "transparent" `div` wrapper (needs testing)

(b) PTX-p id is placed on first non-trivial block element of the busted-up HTML blocks.

(c) `idx` can go anywhere, it will point to the start of the paragraph and "flash" the first constituent of the bust-up.  Because of (1) above, it will be impossible to have the `idx` point to the consituent block.

**Comment by davidfarmer** [comment]
I think I am okay with all of this, including wrapping a div
(with some appropriate class) around display math.  I agree it
is reasonable to wrap display math first, just to check for side-effects.

The math div wrapper will also be useful for other purposes.

**Comment by rbeezer** [comment]
I've started on moving the PTX-p id onto an initial segment of a PTX-p exploded into HTML-p interspersed with various 2-D displays (lists, display math, and `cd`) as an HTML id.  This requires wrapping display math (`me, men, md, mdn`) in something, here a `div.displaymath`.

1.  LaTeX output should be unchanged, the HTML is live (repo, website).  I cannot detect any visual difference.  Sections 7, 6, 5 (in that order) of sample article are good places to look.  @davidfarmer - would you mind having a look?
1.  The class name could be different, or there could be two (or more) to indicate the various displaymath possibilities.
1.  When an `md` or `mdn` has an `intertext` it is output as `p.intertext` (this is not new).  These are now contained inside the `div.displaymath`.  It appears fine.  We **could** explode the `md` into math bits and intertext bits, which would be similar to the PTX-p explosion that is provoking all this in the first place.  This will add an extra layer of complexity, equal to the one being solved right now.  I am really hoping it will be OK for the `p.intertext` to mingle with the `begin{align}` (etc) inside the `div.displaymath`.
1.  See Equations (6.1)-(6.4) in sample article (and an unnumbered version/copy immediately below) for an example of `intertext` just discussed.
1.  I've tested a strategy for migrating the PTX-p id, this should be enough infrastructure to support that.

**Comment by davidfarmer** [comment]
The div.displaymath seems to work well.

Having one div.displaymath enclose all the math and the p.intertext
is legal HTML.  With appropriate ids (see my two questions below,
which I think it your item 5), maybe we can do what we want?

I made some small adjustments to p.intertext .  See if you can
tell what I did, and let me know if you think it needs further
adjustment.

Will p.intertext get an id?  Will div.displaymath?  Is that what
you meant by "migrating the PTX-p id"?

**Comment by rbeezer** [comment]
Perhaps you reduced the vertical spacing around `p.intertext`?  I really can't see much more.

You can't `xref` an intertext, so it won't get an id.  `xref` to equations are handled with mathJax's impersonation of the LaTeX ref/label scheme.  The `div.displaymath` should not get an id of iits own, since it needs to be able to receive the id of the enclosing `p` (which is the thrust of all this work).  For a while I thought I had a real problem with two id's on one item, but now I think that can be avoided.

**Comment by rbeezer** [comment]
I think this is finally done.  A PTX `p` should explode into HTML so that consituent HTML block-level parts are not trapped inside an HTML `p`.  And never should an empty HTML `p` result.  The unique id of the logical PTX `p` should surface on the first HTML element emitted.

This was (and is) very delicate work.  I've tested carefully, but maybe not thoroughly.  Please report empty paragraphs, missing id, misplaced id, double id.  More torture tests can be added to the sample article if there are un-imagined corner cases.

At d26ffb92ba4e76329d96356be73a7404cec5ca83 and mostly 373be9592779cbb1ec5297e84090bc4f70ef53d6.
