### ISSUE TITLE
Indexing inside of Assemblages links to Subsection instead of Assemblage

### ISSUE THREAD

**Issue by nwintersgill** [rbeezer/mathbook#753]
While working on indexing, I found that the index entry created when the `<idx>` tag is used inside of `<assemblage>` tags links to the subsection that the assemblage is in rather than creating a knowl that displays the contents of the assemblage. It's worth noting that even inside `<p>` tags within the assemblage, the index entry still links to the subsection.

There's an example of this in the sample article. The index entry for "assemblage" links to a subsection, despite the `<idx>` tags being located within `<p>` tags within `<assemblage>` tags.

**Comment by Alex-Jordan** [comment]
From an example of this we encountered where `idx` was inside a `tabular`, the _link_ from the index was "correct". It was appended with `#tabular-2` at the end. But there was not HTML ID `tabular-2` on any element of the page. So it appeared that you were linked to the section instead of the thing within the section.

Of course, it would be better if there were a knowl for the tabular, and the index opened that knowl.

**Comment by davidfarmer** [comment]
A principle which was mentioned in pretext-support is
' "idx" anywhere inside a block/environment is to reference the block/environment '

I think that is reasonable.  But note that (sub)sections are not a type of block/environment
that should be referenced.  And therefore(?) neither are paragraphs.

**Comment by rbeezer** [comment]
An `assemblage` was not reporting itself as a block, and so the index code just kept looking up the tree until it saw an enclosing division.

Fixed at f2f5b743c709f638719a3208761d2dfeac907f92

**Comment by rbeezer** [comment]
> And therefore(?) neither are paragraphs.

Blocks are children of divisions.  So a `p` that is a child of a division is handled like a block, while a `p` **inside** a block is not.
