### ISSUE TITLE
Enable titles on hints, answers, solutions

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#764]
From:  https://groups.google.com/d/topic/pretext-support/wPial4khaeI/discussion

**Comment by rbeezer** [comment]
Thanks, Joe @sepvar, for the excellent suggestion.

Implemented, with example, at ed45dc7e59f750b1cb7a635bff07103a5aa1357f.

Schema expanded at 2ac480fe6f79f5259e8da01eecfde201c4c970c7.

**Note**  HTML output needs some CSS work, and maybe back matter use needs further attention for both LaTeX and HTML.

**Comment by davidfarmer** [comment]
Maybe Joe can provide some actual examples,
because the "MVT", "Motivator" and "Helpful"
titles are not sufficiently helpful to motivate me to
figure out a good styling.  Apologizes if I am being mean.

My guess is to make the title in the knowl link smaller and wrap
it in parentheses, but would prefer to have real examples for
testing.

Were all the examples at the end of Section 16?

**Comment by sepvar** [comment]
Yeah, you betcha:
Caution: These are three that I have in my head.  I might be able to find others and now that it is an option, I expect I will make good use of it.  I did not re-write these examples in a way that makes goo use of the titles, because I think the format might alter how I phrase the reference to a titled hint, but I modified these three to give you some variety to consider.

I am attach three screen shots so that you can see a before and after.  I did not upload the new version to the server, but I think you can look at the link provided to each of the old versions online, glance at the screen shot of the new version and get a sense of what title I would use.  **Let me know if you would like more detail or a full example written to accommodate the titles.**

Example 1: (worst of the three, example is not even complete)
Link: http://physics.thomasmore.edu/ConnectedPhysics/ss-multistep.html
Screen-shot: Section multistep, example ceiling: 
![multistep ceiling](https://user-images.githubusercontent.com/24879607/32148429-2cee842e-bccd-11e7-967a-fb97da45d63c.jpg)

Example 2: better example in the book.  Example 8.4.33
Link: http://physics.thomasmore.edu/ConnectedPhysics/sss-kinetic.html#ex-friction-mug 
Screen-shot: Example of how far the mug slides: 
![sliding the mug](https://user-images.githubusercontent.com/24879607/32148448-93e4e1c8-bccd-11e7-8241-6fb18313c855.jpg)

Example 3: reasonable example from the lab manual. Exercise 8.4
Link: http://physics.thomasmore.edu/PHY121Lab/s-energy2-procedure.html
Screen-shot: Exercise regarding predicting the graphs of energy versus time: 
![making energy graphs](https://user-images.githubusercontent.com/24879607/32148472-f72be182-bccd-11e7-9dfa-80989077f996.jpg)

**Comment by davidfarmer** [comment]
I need an actual live online example in order to take care
of the CSS.

**Comment by sepvar** [comment]
Oh, right.  You don't want to read through my whole book from github. Sorry about that.

Please find attached a minimal example with the three examples cited above cut-and-pasted and both html and latex compilable.
[minimal-titled-hints.txt](https://github.com/rbeezer/mathbook/files/1425597/minimal-titled-hints.txt)

Please ignore the \studentC, etc.  I have sed scripts that clean those out for me pre-html and still allow LaTeX to compile it.  (These allow me to change the name or gender of the people in the book globally with an easy adjustment.)

Will that work? or do you want the github link to the full documents?

**Comment by davidfarmer** [comment]
What I need is an HTML version that was made from PreTeXt source.

**Comment by rbeezer** [comment]
On 10/29/2017 04:51 PM, David W. Farmer wrote:
> What I need is an HTML version that was made from PreTeXt source.

Using PreTeXt with a pull sometime after about noon (Pacific) today.

**Comment by sepvar** [comment]
The TXT file I posted last night is the PTX source file, which can be used to make html or LaTeX with 
xsltproc ${MATHBOOK}/xsl/mathbook-html.xsl minimal-titled-hints.ptx
Github wouldn't recognize PTX as an uploadable extension, so I changed the extension to TXT in order to upload it.

On the other hand, I have now uploaded a tar-file to my server, which you can download at:
http://physics.thomasmore.edu/ConnectedPhysics/minimal/minimal-th.tar
It contains the files that you can also access from the http://physics.thomasmore.edu/ConnectedPhysics/minimal/  directory:
minimal-titled-hints.ptx
minimal-titled-hints.tex
minimal-titled-hints.pdf
front-titled-hints.html
section-titled-hints.html
minimal-titled-hints.html

Or you can view them at
http://physics.thomasmore.edu/ConnectedPhysics/minimal/section-titled-hints.html

**Comment by davidfarmer** [comment]
I made an exception this time, and added some styling based on

http://physics.thomasmore.edu/ConnectedPhysics/minimal/section-titled-hints.html

The exception was that usually I am only willing to style
complete actual examples (that are posted online by the author).
Otherwise it often happens that some styling is missed, or the new
styling unintentionally changes something else.

**Comment by sepvar** [comment]
Thank you, David.  If you would like to verify the context more completely, the links next to the screen images above sends you to the specific locations in the books.  As I intended to show with the screen shot, the only difference is that I added titles to the hints, so those links should still give you the sense of it, I think.

I am sorry that I can't post the revisions as part of the full book, I am in the middle of some complex (unrelated) changes that are not ready to be posted and I am not comfortable enough with having multiple github versions to fork a new version while I am so immersed in the current changes just yet.  If you'd rather wait a few days, I hope to have something updated by the end of the week.

**Comment by davidfarmer** [comment]
If styling is needed once you post the new version, just let me
know the link.

**Comment by rbeezer** [comment]
On 10/31/2017 04:46 AM, Joe Christensen wrote:
> I am not sure if this was intentional, but I notice that the knowls don't print
> the type-number-title in the knowl. On the other hand a nested-knowl does print
> the type-number-title in bold. For example, in the minimal-titled-hints html,
> Example 1.3. If I open Hint 4, it does not have a title displayed; but if I open
> Hint 1 (which does not display the title) and then inside Hint 1 click on Hint
> 4, that nested knowl of Hint 4 does display the title.

Intentional.  All that information is in the clickable, so we don't reproduce 
it.  When the knowl is a target of a cross-reference, then we don't know the 
context of the cross-reference, so we provide full information.

**Comment by rbeezer** [comment]
Thanks, David.  Looks good on the sample article.

@sepvar No plans to make PDF/LaTeX style **identical** to the HTML.  They are different formats with different capabilities and needs.
