### ISSUE TITLE
Marking HTML paragraphs coming from logical PTX paragraphs

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#777]
Often we break a PTX `p` into many HTML `p` with various HTML block elements in-between.  By necessity.

Suppose a style wants to indent the start of each PTX `p`.  Do we want to put classes on the first busted-up HTML `p` and something different, or additional, on the later ones?

My motivation (which is a possible improvement, but not needed urgently) is that maybe spacing around these interior bits (math display, lists) could be just a bit tighter than spacing between logical PTX paragraphs.

Spacing is just for even better visual fidelity.  But once a style indents the first line of a paragraph, the HTML is going to mis-represent author's intent.  Grist for the mill while doing CSS paragraphs.

**Comment by Alex-Jordan** [comment]
Should a PTX `p` just become a `div` with a class like `ptx-p`? And then CSS styling could be applied to that `div`'s first `p` differently from other `p` in that `div`?

**Comment by davidfarmer** [comment]
I would prefer to use a p with a class, because I have become more
sensitive to the fact that we want the HTML to be understandable
without the CSS.

We lucked into that with my (at the time, seemingly unreasonable)
insistence that we use h1,....h6 sensibly, even though the CSS
only operates on the classes of the hN.  (The alternate proposal
was to start over with h1 inside each section.)

Another option is to wrap a div around the collection of p's that go
together.  I don't like that idea, but want to think more before
explaining why.

**Comment by Alex-Jordan** [comment]
>Another option is to wrap a div around the collection of p's that go together. I don't like that idea, but want to think more before explaining why.

This is what I actually meant with my last post. All the HTML `p`'s would be there, surrounded by one `div` with a class. The CSS could then distinguish the first HTML `p` from the ones that follow.

**Comment by rbeezer** [comment]
OK, points have been made clearly, we validate fine relative to this, and since David writes the CSS he makes the final decision on items like this.  I'm closing, but we can always re-open.
