### ISSUE TITLE
Caption-less figures

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#79]
Make a `<figure>` and fail to provide a caption.  

HTML XSL will see the figure and count it in the numbering scheme for theorems, et.al.

LaTeX XSL will not output `\caption{}` and it will not be numbered in LaTeX output.

Result: the two outputs have different numbering from there on.

Proposed solution: always put a caption (number) on a figure (even if content is null).  Similarly for tables.

The `<sidebyside>` environment accurately deals with absent captions, so this would be the way to place an image or table without a number, if that is what is desired.

Perhaps eventually there will be a flag to turn off numbers on a per-item basis.

**Comment by davidfarmer** [comment]
I would have to put in

<caption></caption> ?

That is not optimally author-friendly.

How do you handle un-numbered equations, theorems, and sections?  Can't
this be done the same way?

Maybe I have a more basic question.  It I want to insert an image or
table and give it a caption, then I wrap it in a figure environment
and put a caption inside that environment.  But what if I don't want
a caption?  Would it then be silly (or un-necessary) to wrap it in a
figure environment?

If the answer is "yes", then maybe that mitigates my earlier comments.
(Apologies if all this is explained in the sample document.)

**Comment by cmhughes** [comment]
This issue also occurs if you repeat the exercise with a captionless table. 

Perhaps a 'top level' version of `image` and `tabular` could be made? Otherwise the counting of `figure`s and `table`s needs to be tweaked; to count only `figure`s and `table`s that have captions, but not those that are `sub`figures or `sub`tables in `sidebyside`.

**Comment by rbeezer** [comment]
Right - that is exactly what is going on.

Or, as David suggests, institute a number/no-number scheme for figures, tables, 
theorems, etc.

See next message.

**Comment by rbeezer** [comment]
*Right now* you would have to always put in `<caption></caption>` if you wanted 
numbering to sync.  I am not suggesting anybody does this.

I'm proposing MBX does the equivalent for you if you do not specify a caption. 
Addind a number/no-number scheme is a summer project when I do not have classes. 
  ;-)

If you put in an image now, it is just fine.  But you get no line break, no 
centering, no nothing.  Same for a tabular.

Short-term solution: put image into a side-by-side all by itself (with lots of 
placement control).
Long-term solution: allow figures without captions and without numbers.

An `<image>` should be just that - an image.  Figure, sidebyside, sidebar should 
all be devices that place it somewhere.  The minute you add some extra stuff 
around the image *every time*, then it'll be inappropriate in some instance.

Does that sound rational?  Not explained in the sample article - just dawned on 
me while fixing a caption-less image Tom Judson has in the algebra book.

Rob

**Comment by davidfarmer** [comment]
I think it is reasonable to abuse the sidebyside tag for now,
and do it properly later.  Having a collection of use cases
will help when you have time to do it properly.  I have lots
of SL2X examples where there are tables and images not in a
figure environment.  The document goes

text

image

text

Currently in the html I just put a centered img between two
p paragraphs.

Unrelated topic: I am sending this by email, but last time I didn't
get my own reply.  Since I am "watching" rbeezer/mathbook I thought
I would get everything automatically, and you wouldn't have to
specifically cc me.

**Comment by rbeezer** [comment]
Resolved at 96634879

Caption-less figures and tables now mirror caption-less side-by-sides.  Somewhat contrary to discussion above, they are *always* unnumbered.  This gives them utility as a way to center and break an image or a table.

#146 will implement titles, which will provide a way to have these be a target of a cross-reference.
