### ISSUE TITLE
Title page of book

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#799]
On the opening HTML page of a book:

http://mathbook.pugetsound.edu/examples/sample-book/html/

there is an empty paragraph after the date (under the .contributors).

Also, the date is in an address.contributors.  That should have a different class.

The contributors are just a sequence of "p"s and some "br"s.
If we can figure out some better markup, then some better styling could be applied.

**Comment by davidfarmer** [comment]
Also, the section on that page has id="index" which I don't think is useful for anything.

**Comment by Jahrme** [comment]
I believe that the `id="index"` comes from the `xml:id` on the sample book’s frontmatter which is set to be “index” so that the title page is created as index.html and this serves as the default page.

**Comment by rbeezer** [comment]
Agreed, this needs reworking just like we did for some of the `colophon` items.

Jahrme is right about the `id="index"`.  Messing around with the author-supplied `@xml:id` to get a default `index.html` page has had unintended side-effects I'm not happy with.  I'm in agreement with the behavior, but it is HTML-specific and has consequences for other conversions.  So needs to be re-worked.

You can probably find other un-useful `id` that are a consequence of modular and generalized routines that lead to simple code and more reliable, consistent output.

**Comment by davidfarmer** [comment]
It is fine with me for the HTML to contain ids that may not be used
(including "index" as an id).

**Comment by rbeezer** [comment]
Empty paragraph is gone (I think it was there to make vertical space, and is not the **other** empty paragraph problem).

Authors and editors now look like contributors, a `div.author-name`, followed by a `div.author-info`.  Latter is a sequence of "lines" separated by `br`.  Each author/editor has all of this wrapped in a `div.author`.  CSS does not distinguish editors, since PTX writes `, Editor` in document language.

A `credit` is similar, but has a required title and should be rendered not as prominently as the main authors/editors.  So an enclosing `div.credit` to allow for different treatment (note we have a `p.credit` in the front colophon).  The title comes first in a `div.title` followed by a person's name and info, with same classes as full author/editor (i.e., as above).  There can be several names associated with a single title.

The date is last, and now in a `time` element, which should hold "human readable" time.  I also gave it a `.time` class.

Test version at http://mathbook.pugetsound.edu/beta/20180127-title-page/index.html.

Send modifications or let me know when CSS is ready and I can merge commit to make it live.

Rob

**Comment by davidfarmer** [comment]
I added some styling, but more work is needed.

About "time".  It is fine to use the time element, but then the
class should be something different.  How about "version" or "date"?

I'll do more once more examples are available.

**Comment by rbeezer** [comment]
Thanks, David.  I changed `time.time` to `time.date`.  I think we should reserve `.version` for something more serious and/or for the "copyright page" (ie front colophon).

Live now.  I think one of Alex's projects has a bunch of authors and credits - maybe when he next rebuilds that then there will be a super-complicated example.

How do you feel about centering these items?  I've always wanted this page to look as "book-like" as possible.  I think centering would give it more of that feel of a "real" title page.  It is not identical, since we typically have some navigation below, but I think it is a good place to reinforce our commitment to Principle 4 (centuries of book design).

Rob

**Comment by davidfarmer** [comment]
I added some centering and some small tweaks.

Probably need some more examples to get every case right.

Maybe close this and treat remaining problems as a separate issue?

**Comment by rbeezer** [comment]
Looks good.  Thanks for adding the centering - I like that look.

Yes, lets just iterate from here as projects with more complicated title pages surface.
