### ISSUE TITLE
Class for internal links

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#800]
I suggest adding a class (internal ?) to the links between sections of a document.
For example, the Subsection 27.1 link on this page:

http://mathbook.pugetsound.edu/examples/sample-article/html/interesting-corollary.html

Recent change to the CSS have removed the color from such links.  The best way
to put it back is to mark up the fact that it is a link within the document.

If we want some different styling on external links, then those should also get a class.

Also, I think it looks better to call that link "Section 27.1".  Especially when you get
to Subsubsection, the reader is being given too much information, and just writing
"Section" looks more natural.

**Comment by rbeezer** [comment]
Sixty-four places where the code makes an `a` element, so I did not patrol them all.  A PTX `xref` that points to something "big", like a `section`, now has a `.xref` class.  (The difference being an `xref` that becomes a "small" knowl, which should have enough identification to style.)

A PTX `url` becomes an HTML `a` with a `.external-url` class.  It has always been this way, since September 2013, 2b26187476d95aa0c60e5d31bf1da5f08090e2f7.  ;-)  I took this overhaul as an opportunity to shorten it to `.url`, which is also what it is.

Live now, work at  788e7254755e9340d029eec2d415ddd3c14e7364

Lots of internal/xref variants in the index, and in cross-referencing demos:

http://mathbook.pugetsound.edu/examples/sample-article/html/section-cross-referencing.html

External/URL in the very first paragraph.  It has always been this way.  ;-)

http://mathbook.pugetsound.edu/examples/sample-article/html/section-1.html

**Comment by rbeezer** [comment]
I'm moving discussion of a new xref style to a new issue, #802.  And so closing this one now.

One job per issue will make it easier for me to keep these all neat and tidy.

Thanks for the work styling these.

**Comment by davidfarmer** [comment]
What do you think of class="internal" instead of class="xref" when the hyperlink is to
another page in the same document?

**Comment by rbeezer** [comment]
That'd be fine - names in CSS are your call.

Want me to change to that?

**Comment by davidfarmer** [comment]
I'll change it, after I think a bit more.  I am concerned that other
use cases will be found (links in the margin, for example) and don't
want to make a choice that has to be redone.

**Comment by rbeezer** [comment]
Sounds good.  This will tell you every place an `xref` can appear:

http://mathbook.pugetsound.edu/doc/schema/schemas/pretext_xsd/elements/xref.html

One exception is the "reason" for a step of a proof in a math display.  I think it is a `\knowl` or a `\href`, depending on if it is internl or external.  I have no idea about how the latter might be styled.

**Comment by davidfarmer** [comment]
The CSS recognizes both .url and .external for external links,
and .xref and .internal for links.  I am fine with leaving both in the CSS.

In the long run, it would be good to use .internal and .external, because those
are more descriptive and unambiguous.  But I don't feel a need to change it right now.
