### ISSUE TITLE
name for `men`

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#83]
I have `autoname="yes"` for my whole document. When I have a `<men>` element, and I refer to it, there seems to be no entry in the localization file for this. So instead of *Equation 1.2.3*, I get a warning message from the `xsltproc`, and *[men] 1.2.3* in the output.

**Comment by rbeezer** [comment]
That's because I (wrongly) assumed that parentheses (eg, simply `(4.2)`) would be clue enough for a reader.

So now "Equation" exists in the English localization.  And the `<men>` and `<mrow>` elements are fully integrated into the autonumbering scheme.  The result is that you get `Equation (4.2)`.  I'm inclined to leave in the parentheses.  The first argument for this is that this is the LaTeX behavior automatically from `\eqref`.  But it also helps identify the difference between Theorem 4.2, Equation (4.2), and reference [4.2].

Samples in the "Cross-Referencing" section of the sample article.  Not all permutations fully-tested, but the code is quite modular and I expect it all should work.  Please report if it is otherwise.

Fix at: a262802e
