### ISSUE TITLE
Different tabular outputs

### ISSUE THREAD

**Issue by cmhughes** [rbeezer/mathbook#89]
Consider the following table:

```
<tabular top="major" halign="center">
                    <col halign="left"/>
                    <col halign="left"/>
                    <row> <cell bottom="medium" right="major">123</cell><cell>1234</cell></row>
                    <row> <cell>12</cell><cell>123</cell></row>
                </tabular>
```

When I transform this into `html` I get:

![screenshot from 2015-05-03 17 52 02](https://cloud.githubusercontent.com/assets/2224480/7445875/282d1db6-f1bd-11e4-8d1c-4fbe9b7cdbe1.png)

When I transform into `LaTeX` I get:

![screenshot from 2015-05-03 17 52 43](https://cloud.githubusercontent.com/assets/2224480/7445880/3d114a0e-f1bd-11e4-844f-d82b09a52c95.png)

I believe that this behaviour isn't as intended :) I'm working off the latest version of the `develop` branch.

**Comment by rbeezer** [comment]
Dear Chris,

Yes, the LaTeX side looks wrong.  I suspect I can track it down once I convert 
your example into the raw LaTeX.  Thanks for providing a good example.

Rob

**Comment by rbeezer** [comment]
Good catch.  Off-by-one examining the condition on the end of a row.  Bug was duplicated for the border along the top, so that is fixed as well.  Thanks again for the report.

Change at c08b9bb1 is isolated at two particular lines and so should not affect your column alignment work, I think.

Thanks,
Rob
