### ISSUE TITLE
Report bad returns from WeBWorK server

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#893]
When the author uses an OPL problem, it may come back with invalid PTX structure because the problem was coded in some PTX-incompatible way. It may even come back as invalid XML. We should report this (either invalid PTX or simply invalid XML) as the mbx script is running. It is currently tedious to track down if you only discover it at some later stage of production.

Even when not an OPL problem, a particular seed or just bad PG coding can cause a Perl error to be returned, which is *really* invalid XML. The string "ERROR" and other identifying strings come back in this case. If the above XML validation is too hard, we should at least warn about this kind of thing while the mbx script is running.

**Comment by rbeezer** [comment]
There is a Python library for working with an XML tree in ways similar to XSLT (but not always the same ways).  You could
* Hit the returned XML with some simple function - perhaps a "well-formed" validator is supplied or you could count the nodes.
* Wrap in a `try/except` block and raise a Python error within the `mbx` script
* Or better, instead of raising an error, recover gracefully with an informative console message (which WW, by id or...) and generate informative stock PTX XML: "your problem would go here, but for a server error..." so everything can proceed and the missing bit is obvious.

**Comment by Alex-Jordan** [comment]
Good progress was made here in #982. If the PG file is empty, or if the PG failed to compile, or if the returned content is not valid XML, these things are all detected. We have an option to abort extraction if these things are found. Or keep going and print a message about the flavor of the issue.

What remains is when valid XML is returned, but it is not valid PTX. In my experience helping others, this most often happens when the OPL problem is very old, and using the `EV2` subroutine to print the question bits instead of `BEGIN_TEXT...END_TEXT` or `BEGIN_PGML...END_PGML`. Without those things, there is no clear way to mark where a statement begins and ends. Time permitting, I should explore `EV2` and see if anything can be done. Including seeing if a simple message can be printed that we latch on to so we know the problem is PTX-incompatible.

Of course that will still leave the door open for valid XML, but invalid PTX, to get through. Could set up the script to apply jing-trang, except we have knowingly allowed WW output to deviate from the schema. "Justified" since we are in control of its creation, not some PTX author.

**Comment by Alex-Jordan** [comment]
I'm going to close this and make a new issue that is specific to validation against some PreTeXt schema, since most of what was wanted here is now in place.
