### ISSUE TITLE
Navigating sections of an appendix in html output

### ISSUE THREAD

**Issue by jjrsylvestre** [rbeezer/mathbook#963]
An appendix seems to behave like a chapter in that it can have sections. But in the lefthand TOC sidebar of html output, an appendix appears as if Back Matter were a chapter and the appendix were a section of Back Matter. Then the only ways to navigate between sections of that appendix are to use the Prev/Up/Next buttons, or to click the appendix in the TOC bar to return to the list of sections page for that appendix (equivalent to using Up). So navigation options for sections in an appendix are inconsistent with those for sections in a regular chapter for toc.level=2.

Not sure of the solution. Should Back Matter be considered a part, with appendices considered chapters of that part?

**Comment by rbeezer** [comment]
Yes, the "backmatter" has evolved a lot of inconsistencies over the years, which 
I am gradually rooting out elsewhere (LaTeX).  Your analysis sounds correct. 
The same should be true of a "subsection" of an "appendix" in an "article", 
since there an appendix should behave like a section.

First step should be to have the schema reflect the difference between 
"book/appendix" and "article/appendix".  Not that this will improve any code.  ;-)

On 09/21/2018 03:03 PM, Jeremy Sylvestre wrote:
> Not sure of the solution. Should Back Matter be considered a part, with 
> appendices considered chapters of that part?

Yes, if I made "Back Matter" behave more like when there are "part", it should 
be a good solution.  David F plans a refactor of the HTML ToC sidebar, so 
perhaps then an even better fix will be in place.

Thanks - I'll take a look in a bit.

**Comment by rbeezer** [comment]
Good catch.  Thanks for reporting this.  Solution was easier than expected.  Limited testing, so holler if it is not right for your project.  At 528c68036a05a048e6b338c9e8a9936d8210f05b.

No change to the schema, though.  Yet.
