### ISSUE TITLE
Improve proof style (tcolorbox)

### ISSUE THREAD

**Issue by oscarlevin** [rbeezer/mathbook#985]
The current setup for the proof environment styling is problematic for a few reasons.

1. The qed symbol is not always flush-right.  If the proof ends filling a line, the square is flush left on the next line.
2. Footnotes appear at the end of the proof, not the end of the page.  This is a larger issue with tcolorbox stuff (see https://groups.google.com/forum/#!topic/pretext-support/5aewLfGb3wg)
3. An easy fix: these should have parbox=false added to their style, so paragraph breaks appear as normal (this might be worth adding to all tcolorbox styles meant to contain p's).

An easy fix would be to go back to the amsthm proof environment, although this has disadvantages too.

**Comment by rbeezer** [comment]
(3) has been corrected at 5ed998c9cbff2b51e6f8ca49344cfb963066e6b6

Announcement on relevant thread on pretext-dev.

**Comment by rbeezer** [comment]
> An easy fix would be to go back to the amsthm proof environment, although this has disadvantages too.

My aim is to remove all dependencies on the AMS document classes (but not the symbol package).  There will be a small regression relative to the tombstone following display mathematics, but I'll try to fix the flush-left problem soon.

**Comment by rbeezer** [comment]
Markers for proofs, definitions, and examples, as part of default/stock LaTeX styling, should now reliably be flush-right once the last line is full-width.  Used a bit of a sledgehammer -- improvements welcome.

At 3caae1503c04f08f653c686c8aea89b1f3dab993

I had to manufacture an example for the sample article, since there were not any existing examples.  Confirmation that this fixes your instances would be appreciated.  Thanks for the report.

**Comment by rbeezer** [comment]
Best currently-possible fix is at 64eeb36cd0c3023dc9a89a8bf6059608532bd4ec, with discussion in Author's Guide at 938b86fa6c4c2005bcda496449808533c952c9e3.

That's a trifecta.
